function Snowball() {
BaseStemmer = function() {
this.setCurrent = function(value) {
this.current = value;
this.cursor = 0;
this.limit = this.current.length;
this.limit_backward = 0;
this.bra = this.cursor;
this.ket = this.limit;
};
this.getCurrent = function() {
return this.current;
};
this.copy_from = function(other) {
this.current = other.current;
this.cursor = other.cursor;
this.limit = other.limit;
this.limit_backward = other.limit_backward;
this.bra = other.bra;
this.ket = other.ket;
};
this.in_grouping = function(s, min, max) {
if (this.cursor >= this.limit) return false;
var ch = this.current.charCodeAt(this.cursor);
if (ch > max || ch < min) return false;
ch -= min;
if ((s[ch >>> 3] & (0x1 << (ch & 0x7))) == 0) return false;
this.cursor++;
return true;
};
this.in_grouping_b = function(s, min, max) {
if (this.cursor <= this.limit_backward) return false;
var ch = this.current.charCodeAt(this.cursor - 1);
if (ch > max || ch < min) return false;
ch -= min;
if ((s[ch >>> 3] & (0x1 << (ch & 0x7))) == 0) return false;
this.cursor--;
return true;
};
this.out_grouping = function(s, min, max) {
if (this.cursor >= this.limit) return false;
var ch = this.current.charCodeAt(this.cursor);
if (ch > max || ch < min) {
this.cursor++;
return true;
}
ch -= min;
if ((s[ch >>> 3] & (0X1 << (ch & 0x7))) == 0) {
this.cursor++;
return true;
}
return false;
};
this.out_grouping_b = function(s, min, max) {
if (this.cursor <= this.limit_backward) return false;
var ch = this.current.charCodeAt(this.cursor - 1);
if (ch > max || ch < min) {
this.cursor--;
return true;
}
ch -= min;
if ((s[ch >>> 3] & (0x1 << (ch & 0x7))) == 0) {
this.cursor--;
return true;
}
return false;
};
this.eq_s = function(s)
{
if (this.limit - this.cursor < s.length) return false;
if (this.current.slice(this.cursor, this.cursor + s.length) != s)
{
return false;
}
this.cursor += s.length;
return true;
};
this.eq_s_b = function(s)
{
if (this.cursor - this.limit_backward < s.length) return false;
if (this.current.slice(this.cursor - s.length, this.cursor) != s)
{
return false;
}
this.cursor -= s.length;
return true;
};
 this.find_among = function(v)
{
var i = 0;
var j = v.length;
var c = this.cursor;
var l = this.limit;
var common_i = 0;
var common_j = 0;
var first_key_inspected = false;
while (true)
{
var k = i + ((j - i) >>> 1);
var diff = 0;
var common = common_i < common_j ? common_i : common_j; 
var w = v[k];
var i2;
for (i2 = common; i2 < w[0].length; i2++)
{
if (c + common == l)
{
diff = -1;
break;
}
diff = this.current.charCodeAt(c + common) - w[0].charCodeAt(i2);
if (diff != 0) break;
common++;
}
if (diff < 0)
{
j = k;
common_j = common;
}
else
{
i = k;
common_i = common;
}
if (j - i <= 1)
{
if (i > 0) break; 
if (j == i) break; 
if (first_key_inspected) break;
first_key_inspected = true;
}
}
do {
var w = v[i];
if (common_i >= w[0].length)
{
this.cursor = c + w[0].length;
if (w.length < 4) return w[2];
var res = w[3](this);
this.cursor = c + w[0].length;
if (res) return w[2];
}
i = w[1];
} while (i >= 0);
return 0;
};
this.find_among_b = function(v)
{
var i = 0;
var j = v.length
var c = this.cursor;
var lb = this.limit_backward;
var common_i = 0;
var common_j = 0;
var first_key_inspected = false;
while (true)
{
var k = i + ((j - i) >> 1);
var diff = 0;
var common = common_i < common_j ? common_i : common_j;
var w = v[k];
var i2;
for (i2 = w[0].length - 1 - common; i2 >= 0; i2--)
{
if (c - common == lb)
{
diff = -1;
break;
}
diff = this.current.charCodeAt(c - 1 - common) - w[0].charCodeAt(i2);
if (diff != 0) break;
common++;
}
if (diff < 0)
{
j = k;
common_j = common;
}
else
{
i = k;
common_i = common;
}
if (j - i <= 1)
{
if (i > 0) break;
if (j == i) break;
if (first_key_inspected) break;
first_key_inspected = true;
}
}
do {
var w = v[i];
if (common_i >= w[0].length)
{
this.cursor = c - w[0].length;
if (w.length < 4) return w[2];
var res = w[3](this);
this.cursor = c - w[0].length;
if (res) return w[2];
}
i = w[1];
} while (i >= 0);
return 0;
};
this.replace_s = function(c_bra, c_ket, s)
{
var adjustment = s.length - (c_ket - c_bra);
this.current = this.current.slice(0, c_bra) + s + this.current.slice(c_ket);
this.limit += adjustment;
if (this.cursor >= c_ket) this.cursor += adjustment;
else if (this.cursor > c_bra) this.cursor = c_bra;
return adjustment;
};
this.slice_check = function()
{
if (this.bra < 0 ||
this.bra > this.ket ||
this.ket > this.limit ||
this.limit > this.current.length)
{
return false;
}
return true;
};
this.slice_from = function(s)
{
var result = false;
if (this.slice_check())
{
this.replace_s(this.bra, this.ket, s);
result = true;
}
return result;
};
this.slice_del = function()
{
return this.slice_from("");
};
this.insert = function(c_bra, c_ket, s)
{
var adjustment = this.replace_s(c_bra, c_ket, s);
if (c_bra <= this.bra) this.bra += adjustment;
if (c_bra <= this.ket) this.ket += adjustment;
};
this.slice_to = function()
{
var result = '';
if (this.slice_check())
{
result = this.current.slice(this.bra, this.ket);
}
return result;
};
this.assign_to = function()
{
return this.current.slice(0, this.limit);
};
};
IndonesianStemmer = function() {
var base = new BaseStemmer();
 var a_0 = [
["kah", -1, 1],
["lah", -1, 1],
["pun", -1, 1]
];
 var a_1 = [
["nya", -1, 1],
["ku", -1, 1],
["mu", -1, 1]
];
 var a_2 = [
["i", -1, 1, r_SUFFIX_I_OK],
["an", -1, 1, r_SUFFIX_AN_OK],
["kan", 1, 1, r_SUFFIX_KAN_OK]
];
 var a_3 = [
["di", -1, 1],
["ke", -1, 2],
["me", -1, 1],
["mem", 2, 5],
["men", 2, 1],
["meng", 4, 1],
["meny", 4, 3, r_VOWEL],
["pem", -1, 6],
["pen", -1, 2],
["peng", 8, 2],
["peny", 8, 4, r_VOWEL],
["ter", -1, 1]
];
 var a_4 = [
["be", -1, 3, r_KER],
["belajar", 0, 4],
["ber", 0, 3],
["pe", -1, 1],
["pelajar", 3, 2],
["per", 3, 1]
];
 var  g_vowel = [17, 65, 16];
var  I_prefix = 0;
var  I_measure = 0;
function r_remove_particle() {
base.ket = base.cursor;
if (base.find_among_b(a_0) == 0)
{
return false;
}
base.bra = base.cursor;
if (!base.slice_del())
{
return false;
}
I_measure -= 1;
return true;
};
function r_remove_possessive_pronoun() {
base.ket = base.cursor;
if (base.find_among_b(a_1) == 0)
{
return false;
}
base.bra = base.cursor;
if (!base.slice_del())
{
return false;
}
I_measure -= 1;
return true;
};
function r_SUFFIX_KAN_OK() {
if (!(I_prefix != 3))
{
return false;
}
if (!(I_prefix != 2))
{
return false;
}
return true;
};
function r_SUFFIX_AN_OK() {
if (!(I_prefix != 1))
{
return false;
}
return true;
};
function r_SUFFIX_I_OK() {
if (!(I_prefix <= 2))
{
return false;
}
{
var  v_1 = base.limit - base.cursor;
lab0: {
if (!(base.eq_s_b("s")))
{
break lab0;
}
return false;
}
base.cursor = base.limit - v_1;
}
return true;
};
function r_remove_suffix() {
base.ket = base.cursor;
if (base.find_among_b(a_2) == 0)
{
return false;
}
base.bra = base.cursor;
if (!base.slice_del())
{
return false;
}
I_measure -= 1;
return true;
};
function r_VOWEL() {
if (!(base.in_grouping(g_vowel, 97, 117)))
{
return false;
}
return true;
};
function r_KER() {
if (!(base.out_grouping(g_vowel, 97, 117)))
{
return false;
}
if (!(base.eq_s("er")))
{
return false;
}
return true;
};
function r_remove_first_order_prefix() {
var  among_var;
base.bra = base.cursor;
among_var = base.find_among(a_3);
if (among_var == 0)
{
return false;
}
base.ket = base.cursor;
switch (among_var) {
case 1:
if (!base.slice_del())
{
return false;
}
I_prefix = 1;
I_measure -= 1;
break;
case 2:
if (!base.slice_del())
{
return false;
}
I_prefix = 3;
I_measure -= 1;
break;
case 3:
I_prefix = 1;
if (!base.slice_from("s"))
{
return false;
}
I_measure -= 1;
break;
case 4:
I_prefix = 3;
if (!base.slice_from("s"))
{
return false;
}
I_measure -= 1;
break;
case 5:
I_prefix = 1;
I_measure -= 1;
lab0: {
var  v_1 = base.cursor;
lab1: {
var  v_2 = base.cursor;
if (!(base.in_grouping(g_vowel, 97, 117)))
{
break lab1;
}
base.cursor = v_2;
if (!base.slice_from("p"))
{
return false;
}
break lab0;
}
base.cursor = v_1;
if (!base.slice_del())
{
return false;
}
}
break;
case 6:
I_prefix = 3;
I_measure -= 1;
lab2: {
var  v_3 = base.cursor;
lab3: {
var  v_4 = base.cursor;
if (!(base.in_grouping(g_vowel, 97, 117)))
{
break lab3;
}
base.cursor = v_4;
if (!base.slice_from("p"))
{
return false;
}
break lab2;
}
base.cursor = v_3;
if (!base.slice_del())
{
return false;
}
}
break;
}
return true;
};
function r_remove_second_order_prefix() {
var  among_var;
base.bra = base.cursor;
among_var = base.find_among(a_4);
if (among_var == 0)
{
return false;
}
base.ket = base.cursor;
switch (among_var) {
case 1:
if (!base.slice_del())
{
return false;
}
I_prefix = 2;
I_measure -= 1;
break;
case 2:
if (!base.slice_from("ajar"))
{
return false;
}
I_measure -= 1;
break;
case 3:
if (!base.slice_del())
{
return false;
}
I_prefix = 4;
I_measure -= 1;
break;
case 4:
if (!base.slice_from("ajar"))
{
return false;
}
I_prefix = 4;
I_measure -= 1;
break;
}
return true;
};
this.stem =  function() {
I_measure = 0;
var  v_1 = base.cursor;
lab0: {
while(true)
{
var  v_2 = base.cursor;
lab1: {
golab2: while(true)
{
lab3: {
if (!(base.in_grouping(g_vowel, 97, 117)))
{
break lab3;
}
break golab2;
}
if (base.cursor >= base.limit)
{
break lab1;
}
base.cursor++;
}
I_measure += 1;
continue;
}
base.cursor = v_2;
break;
}
}
base.cursor = v_1;
if (!(I_measure > 2))
{
return false;
}
I_prefix = 0;
base.limit_backward = base.cursor; base.cursor = base.limit;
var  v_4 = base.limit - base.cursor;
r_remove_particle();
base.cursor = base.limit - v_4;
if (!(I_measure > 2))
{
return false;
}
var  v_5 = base.limit - base.cursor;
r_remove_possessive_pronoun();
base.cursor = base.limit - v_5;
base.cursor = base.limit_backward;
if (!(I_measure > 2))
{
return false;
}
lab4: {
var  v_6 = base.cursor;
lab5: {
var  v_7 = base.cursor;
if (!r_remove_first_order_prefix())
{
break lab5;
}
var  v_8 = base.cursor;
lab6: {
var  v_9 = base.cursor;
if (!(I_measure > 2))
{
break lab6;
}
base.limit_backward = base.cursor; base.cursor = base.limit;
if (!r_remove_suffix())
{
break lab6;
}
base.cursor = base.limit_backward;
base.cursor = v_9;
if (!(I_measure > 2))
{
break lab6;
}
if (!r_remove_second_order_prefix())
{
break lab6;
}
}
base.cursor = v_8;
base.cursor = v_7;
break lab4;
}
base.cursor = v_6;
var  v_10 = base.cursor;
r_remove_second_order_prefix();
base.cursor = v_10;
var  v_11 = base.cursor;
lab7: {
if (!(I_measure > 2))
{
break lab7;
}
base.limit_backward = base.cursor; base.cursor = base.limit;
if (!r_remove_suffix())
{
break lab7;
}
base.cursor = base.limit_backward;
}
base.cursor = v_11;
}
return true;
};
this['stemWord'] = function(word) {
base.setCurrent(word);
this.stem();
return base.getCurrent();
};
};
return new IndonesianStemmer();
}
wh.search_stemmer = Snowball();
wh.search_baseNameList = [
 "20240530.html"
];
wh.search_titleList = [
 "???"
];
wh.search_wordMap= {
"ثَلَاثُ": [0],
"ثَلَاثٍ": [0],
"ثَلَاثَ": [0],
"hali": [0],
"gulam": [0],
"mempunyai": [0],
"عاينة": [0],
"kepemilkan": [0],
"لِدُنْيَا": [0],
"وَلْيَقُلْ": [0],
"أَحَدُهُمَا": [0],
"إِحْدَى": [0],
"mengganti": [0],
"فَقَامَ": [0],
"taufik": [0],
"mencelanya": [0],
"siapakah": [0],
"فَدَارَ": [0],
"binti": [0],
"فَقَطَّعَ": [0],
"melaluinya": [0],
"أَمْرِي": [0],
"نِسَاءَنَا": [0],
"saja": [0],
"فَقَالَ": [0],
"شَهْرَيْنِ": [0],
"merupakan": [0],
"daging": [0],
"membagi": [0],
"أَجَلٍ": [0],
"كَانَتْ": [0],
"walad": [0],
"urusanku": [0],
"sama": [0],
"iman": [0],
"imam": [0],
"kendaraan": [0],
"menyodorkan": [0],
"حِرَامٍ": [0],
"هَكَذَا": [0],
"sanggup": [0],
"آخَرَ": [0],
"حَدَّثَنَازَ": [0],
"فَجَعَلْنَاهَا": [0],
"saksi": [0],
"شُفْعَةً": [0],
"memandang": [0],
"tsabit": [0],
"أَبَاهُ": [0],
"ditawarkan": [0],
"تَمْرَةً": [0],
"bersikap": [0],
"فَلَا": [0],
"jelas": [0],
"atasnya": [0],
"الغَرِبِ": [0],
"sumpah": [0],
"جَاءَهُ": [0],
"وَاعْدِلُوا": [0],
"melewati": [0],
"rabbmu": [0],
"إِلَيْنَا": [0],
"memerdekakan": [0],
"فَكُلُكُمْ": [0],
"redaksi": [0],
"berfirman": [0],
"sumur": [0],
"الله": [0],
"pengantar": [0],
"dipuji": [0],
"وَقَالُوا": [0],
"sang": [0],
"diberikan": [0],
"bagaimanakah": [0],
"tempat": [0],
"آلَافِ": [0],
"sana": [0],
"menanggung": [0],
"menukar": [0],
"تَحْقِرَنَّ": [0],
"وَتَرْغَبُونَ": [0],
"membaca": [0],
"hari": [0],
"hadits": [0],
"لِمَنْ": [0],
"remeh": [0],
"الْمَرَادُ": [0],
"saorang": [0],
"الرَّاحِلَةَ": [0],
"بِهَامَالًا": [0],
"harb": [0],
"anak-anaknya": [0],
"juraij": [0],
"alasannya": [0],
"الا": [0],
"mengolah": [0],
"wasaltam": [0],
"فَأَسْرَجْتُهُ": [0],
"hadirat": [0],
"يَسْتَحِقُ": [0],
"الْوَحْشِ": [0],
"gmail.com": [0],
"kabar": [0],
"kirim": [0],
"لِعُتْبَةَ": [0],
"sapi": [0],
"أَعْتَقَهَاوَتَزَوَّجَهَا": [0],
"sa\'id": [0],
"بِالْقَصَبِ": [0],
"menghalangi": [0],
"perbuatan-perbuatan": [0],
"dimerdekakannya": [0],
"فَإِنَّهُمَا": [0],
"أَخْبَرَتْهُ": [0],
"غَيْرَ": [0],
"حَدَّثَنَا": [0],
"غَيْرُ": [0],
"mempelajari": [0],
"يُعْطِيهَا": [0],
"فَحَدَّثْنَاهُ": [0],
"مُسْلِمُ": [0],
"quran": [0],
"مُسْلِمٍ": [0],
"tanah": [0],
"hatim": [0],
"عبد": [0],
"يُشْرَبُ": [0],
"نَخْتَارُ": [0],
"hati": [0],
"إِسْحَاقَ": [0],
"إِسْحَاقُ": [0],
"الْوَلَا": [0],
"فَخِذَيْهَا": [0],
"bertaqwalah": [0],
"tankihuuhunna": [0],
"pahanya": [0],
"خَرَجَ": [0],
"sekedar": [0],
"anas": [0],
"تَحْتَ": [0],
"فِيهِ": [0],
"يُعِيشُكُمْ": [0],
"meminta": [0],
"فَيَقُولَانِ": [0],
"بِمِ": [0],
"anak": [0],
"اني": [0],
"binasa": [0],
"مُنْذُ": [0],
"meminum": [0],
"ujiannya": [0],
"فَقَتَلُوهُ": [0],
"فَمَسَحَ": [0],
"anda": [0],
"rambongan": [0],
"melarikan": [0],
"الْحَقِّ": [0],
"jujur": [0],
"قَيْبِهِ": [0],
"besar": [0],
"النَّمْرَتَيْنِ": [0],
"فَأَعْتَقَنِي": [0],
"بُيُوتِ": [0],
"yahudi": [0],
"رَاعِيَةُ": [0],
"أَرْسَلَ": [0],
"رَاعِيَةٌ": [0],
"نِسَا": [0],
"بِشَعِيرٍ": [0],
"tahunnya": [0],
"بِنْتَ": [0],
"bebas": [0],
"بِنْتُ": [0],
"بِنْتِ": [0],
"banrah": [0],
"makanlah": [0],
"سَابِرَ": [0],
"beban": [0],
"الصَّالِحِ": [0],
"satu": [0],
"فَنُصِبَا": [0],
"طَاوُسٍ": [0],
"dahulu": [0],
"peristiwa": [0],
"barirah": [0],
"mukanya": [0],
"رَكِبْتُ": [0],
"بِبَعْضِ": [0],
"يُفِيءُ": [0],
"تَصْنَعُ": [0],
"ثَلَاثَةَ": [0],
"أَتَى": [0],
"لِلَّهِ": [0],
"النَّفَقَةُ": [0],
"keturunannya": [0],
"peduli": [0],
"الرَّزَّاقِ": [0],
"تَمِيمٍ": [0],
"جَعْفَرُ": [0],
"جَعْفَرٍ": [0],
"اجْتَمَعْنَ": [0],
"فَاشْتَهَيْنَا": [0],
"مَالًا": [0],
"سُحَيْمٍ": [0],
"rambut": [0],
"أَيُّمَا": [0],
"أَخْبَرَاهُ": [0],
"ashbagh": [0],
"kokoh": [0],
"katapun": [0],
"millenial": [0],
"سَيِّدِهِ": [0],
"walid": [0],
"عِبَادَةَ": [0],
"anha": [0],
"مِنْكُمْ": [0],
"لِتُعْتِقَهَا": [0],
"الْمَقْبُرِي": [0],
"يدُ": [0],
"أَكْلِهِمْ": [0],
"anhu": [0],
"اسْتُسْمِيَ": [0],
"اسْتَهَمُوا": [0],
"وَأَعْتِقِينِي": [0],
"sebaik-baik": [0],
"saya": [0],
"bersyair": [0],
"amiriy": [0],
"مَرُّوا": [0],
"وسَلَّمَ": [0],
"berkenan": [0],
"sebaiknyakah": [0],
"يرة": [0],
"حَنِيهَا": [0],
"tidur": [0],
"أَصْدَقُهُ": [0],
"الَّتِي": [0],
"أَهْلِهَا": [0],
"menbuat": [0],
"sembelihannya": [0],
"الْبَحْرِ": [0],
"فَذَبَحَهَا": [0],
"anshariy": [0],
"razzaq": [0],
"basyir": [0],
"فَيَأْتُونَ": [0],
"لَقَبِلْتُ": [0],
"يَرِيدَيْنِ": [0],
"membawa": [0],
"أَيْدِيهِمْ": [0],
"pada": [0],
"نُمَيْرٍ": [0],
"berasal": [0],
"فقالت": [0],
"يرٍ": [0],
"شِقْصًا": [0],
"diikutsertai": [0],
"خِفْتُمْ": [0],
"هُرَيْرَةَ": [0],
"الرَّحْمَنِ": [0],
"perwallan": [0],
"rumah-rumah": [0],
"بَلَغَنَا": [0],
"جَارَةً": [0],
"pernah": [0],
"datng": [0],
"muslim": [0],
"menunggu": [0],
"وَهِيَ": [0],
"حَاجَةً": [0],
"فَحِزْبُ": [0],
"قَاتَلَ": [0],
"sekarang": [0],
"يَبْتَغُونَ": [0],
"بَرَّكَ": [0],
"فَهِيَ": [0],
"بِيَدٍ": [0],
"tamim": [0],
"dalam": [0],
"لِذَلِكَ": [0],
"أَحَدِكُمْ": [0],
"ringkas": [0],
"الْحَسَنِ": [0],
"فقامَ": [0],
"فَضَمَّهَا": [0],
"berserikat": [0],
"tidak": [0],
"dianjurkan": [0],
"مَرْيَمَ": [0],
"mewarisiku": [0],
"berkehendak": [0],
"dunia": [0],
"أُخْرَيَاتِ": [0],
"hindari": [0],
"dibawah": [0],
"مِنْبَرًا": [0],
"يَرْفَعَ": [0],
"lakukanlah": [0],
"persekutuan": [0],
"الْأَسْوَدَانِ": [0],
"أَوَّلِ": [0],
"أَوَّلَ": [0],
"أَصْحَابَهُ": [0],
"menyimpang": [0],
"duduk-duduk": [0],
"شَاةٍ": [0],
"يَاسَوْدَةُ": [0],
"paha": [0],
"حَدَّثَنِي": [0],
"kepemlikian": [0],
"menyisakan": [0],
"bahwasanya": [0],
"pagi": [0],
"campur": [0],
"أَخْبَر": [0],
"rahman": [0],
"فَقَالَتْ": [0],
"waqash": [0],
"ذلك": [0],
"زَوْجَ": [0],
"تُؤْذِ": [0],
"murawih": [0],
"فَكَلَّمَهُمْ": [0],
"صَدَاقِهَا": [0],
"يَحْيَى": [0],
"membereskan": [0],
"مَسْلَمَةً": [0],
"kesetiaan": [0],
"أَحَبُّوا": [0],
"قَاعِدَةٌ": [0],
"radlallahu": [0],
"أُمَّهَاتِ": [0],
"dapatkan": [0],
"nahik": [0],
"awal": [0],
"bukahri": [0],
"الْعَامِرِيُّ": [0],
"nadhar": [0],
"مَنْزِلٍ": [0],
"نُعِينُكَ": [0],
"usamah": [0],
"dzimmi": [0],
"mutsannaa": [0],
"بَلَغَنِي": [0],
"mengembalikan": [0],
"أُخْتِنَا": [0],
"حَظِهِ": [0],
"bibi": [0],
"ternak": [0],
"waddan": [0],
"سَنَةٌ": [0],
"sepatah": [0],
"تَأْدِيبَهَاوَأَعْتَقَهَا": [0],
"basysar": [0],
"disembah": [0],
"عُقَيْلٍ": [0],
"وَالْحِزْبُ": [0],
"عُقَيْلُ": [0],
"kulit": [0],
"tho\'if": [0],
"مَسْلَمَةَ": [0],
"perumpamaan": [0],
"فَكَلَمَتْهُ": [0],
"يُفِي": [0],
"أَلَا": [0],
"يَقِيءُ": [0],
"تُنَا": [0],
"الرِّقَابِ": [0],
"نَهِيكٍ": [0],
"hitam": [0],
"فَأَعْيَاهُمْ": [0],
"سُلَيْمَانُ": [0],
"سُلَيْمَانَ": [0],
"bertanya": [0],
"bertamu": [0],
"dikawininya": [0],
"turunnya": [0],
"memperbincangkannya": [0],
"لَبَنُ": [0],
"bekal": [0],
"لَأَحْلَلْتُ": [0],
"nikahilah": [0],
"syuf\'ah": [0],
"فَقَالُوالَا": [0],
"يَكُونَ": [0],
"seluruhnya": [0],
"يَكُونُ": [0],
"ceritakan": [0],
"وَالَّذِي": [0],
"وَأَكَلَ": [0],
"namana": [0],
"نَصِيبًا": [0],
"الْمِنْهَالِ": [0],
"sakit": [0],
"تُسْلِفَنَا": [0],
"بِوَكَانَ": [0],
"membantu": [0],
"الْحُلَيْفَةِ": [0],
"kejadian": [0],
"rusuk": [0],
"menghibahkan": [0],
"بِيعُوهَا": [0],
"هَوَازِنَ": [0],
"ضَابِعًا": [0],
"فِرَاشِ": [0],
"menarik": [0],
"تَرَوْنَ": [0],
"الْغِفَارِيَّ": [0],
"فَا": [0],
"artinya": [0],
"كَرِيَاءُ": [0],
"الْعَبْدِ": [0],
"saudah": [0],
"الْعَبْدُ": [0],
"dan": [0],
"paman": [0],
"الَّذِينَيَشْتَرُونَ": [0],
"pilihan": [0],
"waktu": [0],
"mengirim": [0],
"نَاوِلُونِي": [0],
"الحمَرَنِي": [0],
"enggan": [0],
"أَعْوَادَ": [0],
"فَى": [0],
"mereka": [0],
"hingga": [0],
"wanita": [0],
"pilih": [0],
"ثُمَامَةُ": [0],
"حَبَّانَ": [0],
"menjad": [0],
"إِنَّ": [0],
"الطَّعَامَ": [0],
"رَعِيَّتِهِ": [0],
"مَوَالِيهِ": [0],
"dengan": [0],
"dibantu": [0],
"الْإِفْرَانِ": [0],
"meminjamiku": [0],
"شِقْصَا": [0],
"فَسَأَلُوهُ": [0],
"أَهْدَتْ": [0],
"نَحْرِ": [0],
"بِدِ": [0],
"minan": [0],
"bila": [0],
"pelananya": [0],
"أُشْهِدَكَ": [0],
"para": [0],
"كُلَّهُ": [0],
"بِقِيمَةِ": [0],
"طَرِيقِ": [0],
"meyukai": [0],
"الْمُؤْمِنِينَ": [0],
"فِي": [0],
"أَلَى": [0],
"فَأَتَوْهُ": [0],
"gandum": [0],
"زُهْرَةَ": [0],
"makhzumiy": [0],
"biji": [0],
"qiyamulail": [0],
"mengumpulkan": [0],
"ضَلَّ": [0],
"النُّعْمَانِ": [0],
"بَيْتِ": [0],
"النُّعْمَانَ": [0],
"حَبْسَ": [0],
"sa\'ad": [0],
"وَأَحَبُّ": [0],
"أَنَّهُيُتْلَى": [0],
"allah": [0],
"نَفْسِكَ": [0],
"tuanmu": [0],
"صَحَابَتِهِ": [0],
"allaa": [0],
"فَمَسْئُولٌ": [0],
"فَأَتَتْ": [0],
"tangannya": [0],
"رَوَاحَةَ": [0],
"seorang": [0],
"الْكِتَابِ": [0],
"عُرْوَةُ": [0],
"عُرْوَةَ": [0],
"وَكَانَ": [0],
"mencegah": [0],
"قِسَمٍ": [0],
"جُرَيْجًا": [0],
"umrah": [0],
"الَّا": [0],
"patuh": [0],
"أُجِيبُهَا": [0],
"يَغْلِبُهُمْ": [0],
"bersabda": [0],
"الزَّادُ": [0],
"ذِي": [0],
"فَقَبِلَهُ": [0],
"إِنْ": [0],
"dikendarai": [0],
"dosa": [0],
"bermanfaat": [0],
"صَبِيرٌ": [0],
"mawaliy": [0],
"ladang": [0],
"nu\'aim": [0],
"تَشْتَرِي": [0],
"تَشْتَرِيَ": [0],
"أَصْنَعُهَا": [0],
"صَدَقَةٌ": [0],
"مَعَنَا": [0],
"كُلِّ": [0],
"كُلُّ": [0],
"kedua": [0],
"كُلَّ": [0],
"فَمَا": [0],
"diminum": [0],
"sederajat": [0],
"كَذَا": [0],
"asy-sya": [0],
"وَجِهَادُ": [0],
"ءَ": [0],
"ءُ": [0],
"أَحَدُهُمْ": [0],
"أَشْبَهُ": [0],
"امْرَاً": [0],
"memohon": [0],
"mendatangi": [0],
"uin": [0],
"الفرج": [0],
"ummahatul": [0],
"ditawan": [0],
"عَذَابٌ": [0],
"وَشَرْطَ": [0],
"أَصَلِّي": [0],
"على": [0],
"harits": [0],
"أَزْوَادِهِمْ": [0],
"jabalah": [0],
"menjadikannya": [0],
"cemoohan": [0],
"memerintahkan": [0],
"يَدًا": [0],
"menulis": [0],
"amalan": [0],
"أَدْرِي": [0],
"mina": [0],
"dia": [0],
"rasululloh": [0],
"أن": [0],
"الْوَلِيدِ": [0],
"habib": [0],
"neraka": [0],
"أو": [0],
"الثَّالِثَةِ": [0],
"membuatnya": [0],
"ينَ": [0],
"menemui": [0],
"menjualku": [0],
"tahukah": [0],
"فَذَرُوهُ": [0],
"habis": [0],
"labbaik": [0],
"berat": [0],
"مُرَاوِجٍ": [0],
"عَائِشَةً": [0],
"عَدْلٍ": [0],
"dihitung": [0],
"عَائِشَةَ": [0],
"فَدَخَلَ": [0],
"عَائِشَةُ": [0],
"washil": [0],
"khudriy": [0],
"كُهُ": [0],
"زَكَرِيَّاءُ": [0],
"as-salamiy": [0],
"orang-orang": [0],
"ashar": [0],
"no2303": [0],
"lakum": [0],
"تَابِبِينَ": [0],
"لِابْنِ": [0],
"terjadi": [0],
"يُمَرَّضَ": [0],
"قَالَفَإِنْ": [0],
"أَقْبَلَ": [0],
"يُبَالِي": [0],
"فَذَهَبَتْ": [0],
"tuanku": [0],
"kalimat": [0],
"biaramu": [0],
"وَجَاءَ": [0],
"berdo": [0],
"وَلِيدَةِ": [0],
"bebaslah": [0],
"ananda": [0],
"kepemilikannyya": [0],
"adukan": [0],
"اسْتَفْتَوْا": [0],
"hasil": [0],
"terlebih": [0],
"أَتُوبُ": [0],
"يُجْلِسْهُ": [0],
"وَسَبُّوهُ": [0],
"فَسَبَّتْهَا": [0],
"membebani": [0],
"diceritakan": [0],
"وَالْعَبْدُ": [0],
"بِمَرِ": [0],
"قَبْلَ": [0],
"taltu": [0],
"قِبَلَ": [0],
"memaksanya": [0],
"فَأَكَلَ": [0],
"menerima": [0],
"أَلِيمٌ": [0],
"kalaulah": [0],
"bisa": [0],
"الْبَهَا": [0],
"وَصَلَّى": [0],
"حُمَيْدٍ": [0],
"حُمَيْدُ": [0],
"ujian": [0],
"sebanyak": [0],
"حُمَيْدِ": [0],
"tanggungan": [0],
"أَوْشَيْءٍ": [0],
"berikanlah": [0],
"إِنَّمَا": [0],
"تَابَعَهُ": [0],
"seragam": [0],
"عَلَى": [0],
"يَمُرُّ": [0],
"ja\'far": [0],
"بِضْعَ": [0],
"perwalan": [0],
"مَكَّةَ": [0],
"ubaid": [0],
"kebiasaan": [0],
"hadiah": [0],
"فَسَعَى": [0],
"بن": [0],
"به": [0],
"فَلَغَبُوا": [0],
"الزُّبَيْرِ": [0],
"فَيُعْطِيهَا": [0],
"السَّاحِلِ": [0],
"فَالْأَمِيرُ": [0],
"menjual": [0],
"فَسَأَلْتُ": [0],
"وَإِنَّ": [0],
"hewan": [0],
"فَعَدَلَ": [0],
"بِشَةَفَذَكَرَتْ": [0],
"melarang": [0],
"seuntai": [0],
"بَايَعْتُهُ": [0],
"berhijrah": [0],
"status": [0],
"وَاللَّهِ": [0],
"يَقْرُنَ": [0],
"manusia": [0],
"الْقُدُورَ": [0],
"ةَ": [0],
"majikanku": [0],
"وَيُحْلُ": [0],
"maa": [0],
"فَوَعَدَهُ": [0],
"bagi": [0],
"menenmui": [0],
"ثَمَانِي": [0],
"جُوعٌفَأَصَابُوا": [0],
"بَعَثْتَ": [0],
"dirhampun": [0],
"sumpahnya": [0],
"bernama": [0],
"mau": [0],
"تي": [0],
"نَرْدَهُ": [0],
"berdin": [0],
"الْبُخَارِيُّ": [0],
"tuanya": [0],
"batasan-batasan": [0],
"menyukai": [0],
"menghancurkan": [0],
"عُمَارَةَ": [0],
"مُنَبِهِ": [0],
"limmul": [0],
"pernikahan": [0],
"ma\'bad": [0],
"siapa": [0],
"لَقِيَ": [0],
"يَا": [0],
"أَذَاكَ": [0],
"jahsyi": [0],
"amatiy": [0],
"الْمُسْلِمُونَ": [0],
"masalah": [0],
"رَجُلَيْنِ": [0],
"سَعِيدٍ": [0],
"قَضَى": [0],
"سَعِيدَ": [0],
"الشَّرِ": [0],
"sirin": [0],
"أَهِلَّةٍ": [0],
"tholhah": [0],
"فَقَالُوا": [0],
"بِسَهْمٍ": [0],
"سَعِيدُ": [0],
"وَلَقَدْ": [0],
"شُرَكَاءَ": [0],
"baik": [0],
"سَعِيدِ": [0],
"perbekalan": [0],
"diminta": [0],
"durhaka": [0],
"بِدَةِ": [0],
"hasan": [0],
"dimiliki": [0],
"radijallahu": [0],
"كِهَا": [0],
"نَفِدَهَا": [0],
"نَحَلْتَ": [0],
"مُدًى": [0],
"mushtaholiq": [0],
"نَحَلْتُ": [0],
"punya": [0],
"نَبْنِي": [0],
"السِّنَّ": [0],
"بِحَجَّةِ": [0],
"عَلِمُوا": [0],
"يُقِيمَ": [0],
"belakangnya": [0],
"عِنْدَ": [0],
"بِعَهْدِ": [0],
"قُحَافَةً": [0],
"طَابَ": [0],
"بِمَا": [0],
"bawalah": [0],
"عِبَتِهِمْفَاحْتَشَى": [0],
"السَّبْيَ": [0],
"mei": [0],
"sabda": [0],
"وَأَمْلَقُوا": [0],
"men": [0],
"فَأُكِلَ": [0],
"maka": [0],
"berseriat": [0],
"حَدَّثَنَاأَنَّسُ": [0],
"أَحَقُّ": [0],
"وَإِنِّي": [0],
"diantara": [0],
"lalai": [0],
"menanyakan": [0],
"baju": [0],
"عَلَيْهِمْ": [0],
"menyertakan": [0],
"شَعِيرٍ": [0],
"اشْتَرَطَ": [0],
"memperolehmu": [0],
"وَسْوَسَتْ": [0],
"mengadukannya": [0],
"dua": [0],
"هِبَتِهِ": [0],
"duh": [0],
"الْعَمَلِ": [0],
"لِلَّذِي": [0],
"حَجَاجٍ": [0],
"تَجَاوَزَ": [0],
"الصَّحِيحَةَ": [0],
"mu\'minin": [0],
"عَلَيْكَ": [0],
"bani": [0],
"لِأَخْرَقَ": [0],
"عَلَيْكِ": [0],
"anjuran": [0],
"pertukaran": [0],
"أَنْيَسْتَأْذِنَ": [0],
"وَقَعَتْالْحُدُودُ": [0],
"إِلَهَ": [0],
"terbagi": [0],
"مَمْلُوكِهِ": [0],
"عَوْنٍ": [0],
"ziyad": [0],
"لَمَّا": [0],
"didapatnya": [0],
"أُحِبُّ": [0],
"يَطْلُبُ": [0],
"بِي": [0],
"أَنَّا": [0],
"mengenainya": [0],
"رَ": [0],
"رِ": [0],
"عَمْرُ": [0],
"تَذَاكَرْنَا": [0],
"namannya": [0],
"أَنَّى": [0],
"جَمَالُهَافَيُرِ": [0],
"بْن": [0],
"الْآخَرُ": [0],
"فَأَخْبَرَتْهُنَّ": [0],
"فَهُوَ": [0],
"mudabbar": [0],
"jumlah": [0],
"تَقُ": [0],
"ummatku": [0],
"كُلُوا": [0],
"تَحْتَسِبَ": [0],
"فَقُلْنَ": [0],
"yataamaa": [0],
"terbaik": [0],
"mengizinkan": [0],
"wasaq": [0],
"الْوَاحِدِ": [0],
"جَدِي": [0],
"kakeknya": [0],
"نَازِلُ": [0],
"مِسْعَهُ": [0],
"بُنَيَّةُ": [0],
"alaihi": [0],
"عَتِيقٌ": [0],
"untuk": [0],
"bangkit": [0],
"mani": [0],
"duduk": [0],
"bara": [0],
"hibah": [0],
"فَهُمْ": [0],
"terbenam": [0],
"فَيَرُوحُ": [0],
"الْأَرْضَ": [0],
"إِمَّا": [0],
"syariat": [0],
"teknologi": [0],
"menempatkan": [0],
"فَسَأَلَنِي": [0],
"كان": [0],
"memmanggilnya": [0],
"adapun": [0],
"husain": [0],
"يَرُدَّ": [0],
"يَرُدُّ": [0],
"اليْسَ": [0],
"الْمَاءُ": [0],
"dikirim": [0],
"penuduh": [0],
"semua": [0],
"أَنْتَ": [0],
"وَاشْتَرَطَ": [0],
"membiarkan": [0],
"الْمَاءِ": [0],
"فَيُقَالُ": [0],
"فَوَقَعُوا": [0],
"semoga": [0],
"فَأَتَتْهُ": [0],
"دِرْعَهُ": [0],
"sesungguhnya": [0],
"ju\'tsum": [0],
"سُنَتِهِنَّ": [0],
"berupa": [0],
"نَصْرٍ": [0],
"masy": [0],
"إِخْوَانَكُمْ": [0],
"berniat": [0],
"إِذْ": [0],
"bagaimana": [0],
"masa": [0],
"hakim": [0],
"مَعْبَدٍ": [0],
"فَكَلِّمِيهِ": [0],
"mendidik": [0],
"بَيْتِي": [0],
"عامٍ": [0],
"kepemilikan": [0],
"diatasnya": [0],
"وَهْبِ": [0],
"hajjaj": [0],
"jika": [0],
"bicara": [0],
"فَأَعْتِقِي": [0],
"لَتَنْظُرُ": [0],
"hidangkanlah": [0],
"هَذَا": [0],
"الْمُغِيرَةِ": [0],
"melaksanakan": [0],
"baru": [0],
"سِنَ": [0],
"وَهْبٍ": [0],
"نَرْجُوأَوْ": [0],
"جُعْشُم": [0],
"sepuluh": [0],
"memasang": [0],
"dikuatkan": [0],
"بِهِ": [0],
"خَلَا": [0],
"tinggalkanlah": [0],
"agar": [0],
"عَامِرًا": [0],
"thohman": [0],
"basi": [0],
"selainnya": [0],
"zurarah": [0],
"ketetapan": [0],
"milikku": [0],
"kubu": [0],
"أَخُوهُ": [0],
"كُنَارَ": [0],
"نَصِيبَهُ": [0],
"menyakitimu": [0],
"kitabulion": [0],
"أَعْطَى": [0],
"gadaikan": [0],
"لَأَحْبَبْتُ": [0],
"esok": [0],
"diberi": [0],
"نَهَى": [0],
"kelinci": [0],
"يَقْسِمُهَا": [0],
"berikan": [0],
"عن": [0],
"kuat": [0],
"وَكَا": [0],
"صَوَاحِبِي": [0],
"kontan": [0],
"فَدَعَا": [0],
"empat": [0],
"mati": [0],
"وَأُهْدِيَ": [0],
"أَمَا": [0],
"فَيَسْقِينَا": [0],
"milikiu": [0],
"فَأَغْلَظَتْ": [0],
"menemuimu": [0],
"وَأَنْعَامُهُمْ": [0],
"الْيَتِيمَةُ": [0],
"pembicaraan": [0],
"بِهِنَّ": [0],
"أَسْفَلِهَا": [0],
"kuda": [0],
"بِالْعَتَاقَةِ": [0],
"رَأْسَهُ": [0],
"فَلَهُ": [0],
"دَخَلْتُ": [0],
"umayyah": [0],
"sudah": [0],
"رَابِعَةٍ": [0],
"وَأَوْثَقُ": [0],
"دِينَارٍ": [0],
"مِنْهُمَا": [0],
"خَلَّادُ": [0],
"مِنْهُ": [0],
"bawa": [0],
"ihram": [0],
"صَوْ": [0],
"الْحُدُودُوَصُرِفَتْ": [0],
"وَلِيَ": [0],
"فَوَلَدَتْ": [0],
"kelonggaran": [0],
"غَضْبَانُ": [0],
"pertanggung": [0],
"عَهِدَ": [0],
"keluarganya": [0],
"diringkas": [0],
"tampan": [0],
"حَقٌّ": [0],
"حَقَّ": [0],
"أَنِّي": [0],
"يَقُولُنَهَى": [0],
"seharga": [0],
"فَسَأَلْنَهَا": [0],
"هِجْرَتُهُ": [0],
"shahaabiyah": [0],
"zakatnya": [0],
"عَلَيْهِ": [0],
"ashim": [0],
"الصَّدَقَةِ": [0],
"زِلْتُ": [0],
"أَبْيَاتٍ": [0],
"bayi": [0],
"لِسَيِّدِهِ": [0],
"أَبْيَاتِ": [0],
"فَعَقَرْتُهُ": [0],
"أَرْضَى": [0],
"juwairiyah": [0],
"menyerahkannya": [0],
"فَلَمْ": [0],
"bawah": [0],
"الْأَنْصَارِ": [0],
"الْوَحْيَ": [0],
"اختصره": [0],
"negara": [0],
"barulah": [0],
"terserang": [0],
"بِيَدِهِ": [0],
"مَعَهُم": [0],
"الرَّاعِي": [0],
"فَإِنَّا": [0],
"radliallahu": [0],
"بِهَدَا": [0],
"memakannya": [0],
"muqatil": [0],
"ajaran-ajaran": [0],
"وَالْجَمَالِ": [0],
"milikmu": [0],
"jadi": [0],
"أَمَّاالسِّنُ": [0],
"رُو": [0],
"harafiah": [0],
"صَوْمَعَتَهُ": [0],
"kubayar": [0],
"كَانَ": [0],
"denganmu": [0],
"bersaksi": [0],
"pembantunya": [0],
"hakam": [0],
"غُنْدَرٌ": [0],
"ابْتُهُ": [0],
"غُنْدَرُ": [0],
"suhaim": [0],
"لِلنَّبِيِّ": [0],
"bisyir": [0],
"بِسَهْرٍ": [0],
"لَهُمُ": [0],
"أَكُلَّ": [0],
"tholib": [0],
"ma\'rur": [0],
"لَهُمْ": [0],
"وَأَخْبَرَنِي": [0],
"صَدَقَةٌفَإِنْ": [0],
"bukhariy": [0],
"مِائَةَشرط": [0],
"فَاتَّقُوا": [0],
"عَزْرَةُ": [0],
"syafaat": [0],
"فَخَرَجْنَا": [0],
"سُويْدٍ": [0],
"رَبَّكَ": [0],
"بِالْمَدِينَةِ": [0],
"komitmen": [0],
"أَيُّ": [0],
"يُعْتَقُ": [0],
"kepadanya": [0],
"nashr": [0],
"فَلَقِيَهُمْ": [0],
"transaksi": [0],
"أَجْرُهُ": [0],
"diperoleh": [0],
"wudhukanlah": [0],
"kecual": [0],
"أَفْعَلْ": [0],
"وَسَابِرُ": [0],
"الطَّائِفِ": [0],
"صَاعُ": [0],
"في": [0],
"سُرَاقَةُ": [0],
"قد": [0],
"تَغْرُبَ": [0],
"فَجَاءَ": [0],
"memperbaiki": [0],
"biaranya": [0],
"bukit": [0],
"أَبَا": [0],
"الَهُ": [0],
"a\'masy": [0],
"صَاحِبَهُ": [0],
"membelinya": [0],
"memilih": [0],
"مَلُوا": [0],
"يَمِينِهِ": [0],
"حَنَةٌوَاحِدَةً": [0],
"وَلْيُلْبِسْهُ": [0],
"قَدِمْتُ": [0],
"bai\'atlah": [0],
"بِرُّ": [0],
"قَلِيلَةَ": [0],
"لَيْلَةٌ": [0],
"زَكَرِيَّاهُ": [0],
"لَيْلَةً": [0],
"جُبَيْرٍ": [0],
"كل": [0],
"لا": [0],
"لَحْمُ": [0],
"kuku": [0],
"sedikit": [0],
"undian": [0],
"maharnya": [0],
"عَبَّادٍ": [0],
"إِنَّهُنَّ": [0],
"مِنَّا": [0],
"رَاةٍ": [0],
"wangi": [0],
"menghibahkannya": [0],
"rata-rata": [0],
"menyebutkan": [0],
"كِتَابَتَكِ": [0],
"بَعَثَ": [0],
"سَأَلَ": [0],
"turunlah": [0],
"فَعَجِلَ": [0],
"وَدَعِيهِمْ": [0],
"lembaran": [0],
"memecahkan": [0],
"bebaskan": [0],
"وَعَلَى": [0],
"meminta-minta": [0],
"قَوْلُهُ": [0],
"بِطَعَامٍ": [0],
"dihibahkannya": [0],
"abdullah": [0],
"mengasingkan": [0],
"النَّضْرِ": [0],
"النَّضْرُ": [0],
"كَيْسَانَ": [0],
"قَلَّ": [0],
"وَأَعْتَقِيهَا": [0],
"hidup": [0],
"الْأَشْعَثَ": [0],
"عُضْوًا": [0],
"وَالْمِسْوَرَ": [0],
"قَبِلَهُ": [0],
"menangkap": [0],
"حُبَّ": [0],
"hartanya": [0],
"antara": [0],
"seraya": [0],
"membunuh": [0],
"bersumpah": [0],
"tidurnya": [0],
"زهْرَةً": [0],
"عَنْكِ": [0],
"يَحْلِفُ": [0],
"hasanuddin": [0],
"خَطِيبًا": [0],
"فَنِيَتْ": [0],
"جَالِسًا": [0],
"الْأَشْرَفِ": [0],
"سَلَفَ": [0],
"أَبِي": [0],
"الْمُسَيَّبِ": [0],
"الْإِسْلَامَ": [0],
"فَأَحْمَرْتُهُ": [0],
"وا": [0],
"sembilan": [0],
"menakdirkannya": [0],
"أَسْمَاء": [0],
"أَخِيهِ": [0],
"عَبَّاسُ": [0],
"عَبَّاسٍ": [0],
"أَبُو": [0],
"tebus": [0],
"tangan-nya": [0],
"ribu": [0],
"tetap": [0],
"bahwa": [0],
"memperpanjang": [0],
"membalas": [0],
"الرَّسُولَ": [0],
"وَ": [0],
"بَعِيرًا": [0],
"وِ": [0],
"yasar": [0],
"نِعْمَ": [0],
"فَإِنَّهُ": [0],
"وَأَنِّي": [0],
"أَنْصِبَاؤُهُمْ": [0],
"يَأْتِنِي": [0],
"يا": [0],
"فَأَعِينُوهُمْ": [0],
"أَتَتْهُ": [0],
"rumahnya": [0],
"asuhan": [0],
"ekor": [0],
"مَيْسَرَةَ": [0],
"sesuatupun": [0],
"مُحْرِمُونَ": [0],
"hr.shahih": [0],
"أَرْسَلَتْ": [0],
"diatas": [0],
"كُلُّكُمْ": [0],
"فَاعْتِقَاكَ": [0],
"pahala": [0],
"مُوسَى": [0],
"فَأَعْتَقْتُهَا": [0],
"bukan": [0],
"وُهَيْبٌ": [0],
"tuhannya": [0],
"الْقَابِمِ": [0],
"مَسْئُولَةٌ": [0],
"عَنْهُ": [0],
"mengabarkan": [0],
"وَقَعَتْ": [0],
"mendengar": [0],
"يَوْمَ": [0],
"يَوْمٍ": [0],
"era": [0],
"langsung": [0],
"selamat": [0],
"يَوْمِ": [0],
"آدَمَ": [0],
"آدَمُ": [0],
"menangguhkannya": [0],
"بِغَيْرِ": [0],
"radilallahu": [0],
"tidakberlaku": [0],
"dipanggil": [0],
"ditimbang": [0],
"دَيْ": [0],
"حَدَّكنا": [0],
"uang": [0],
"gigi": [0],
"الْأَشْعَرِنِينَ": [0],
"belum": [0],
"pantai": [0],
"أُكْلَةً": [0],
"يَنْصَحُ": [0],
"الْقَاسِمِ": [0],
"بِيَدِهَا": [0],
"mencampuri": [0],
"berharga": [0],
"perkataan": [0],
"menjalankan": [0],
"نَسَمَةٍ": [0],
"رَأَيْتُ": [0],
"احْتَجِبِي": [0],
"الْحَارِثِ": [0],
"مِنِّي": [0],
"دِرْهَم": [0],
"بِهَدَايَاهُمْ": [0],
"وَذَكَرُهُ": [0],
"قَيْسٍ": [0],
"بْنِ": [0],
"سَوْدَةُ": [0],
"رَقَبَةٍ": [0],
"diundang": [0],
"وَخُيِّرَتْ": [0],
"فَأَصَابَتْنَا": [0],
"بْنَ": [0],
"مِنِّى": [0],
"بْنُ": [0],
"فَكَسَرَتْ": [0],
"قَذَ": [0],
"firmannya": [0],
"syarat-syarat": [0],
"فَبُسِطَ": [0],
"bekerja": [0],
"يَسَارِهِ": [0],
"berkata": [0],
"اقْتَرَأَ": [0],
"musuh": [0],
"tetangga": [0],
"zubair": [0],
"kurang": [0],
"بَلَى": [0],
"نَرْهَنَّكَ": [0],
"فَرَجَعَ": [0],
"وَأَحْبَبْنَا": [0],
"فَإِنَّ": [0],
"rabi\'ah": [0],
"وَأَحَبُّوا": [0],
"قَدْ": [0],
"فَأَبْصَرْتُهُ": [0],
"تُؤْذِينِي": [0],
"مَنْ": [0],
"نَجَوْا": [0],
"hurairah": [0],
"اسْتَأْنَيْتُ": [0],
"نُؤْمَرُ": [0],
"فَكَلَّمَ": [0],
"media": [0],
"islam": [0],
"نُصَلِّي": [0],
"لِأَحَدِهِمْ": [0],
"يَتَرَوْجَهَا": [0],
"الْمُسْلِمَاتِ": [0],
"وَلْتُهُ": [0],
"hak-hak": [0],
"qiyamat": [0],
"amrah": [0],
"وَعَتَقَ": [0],
"عَوَانَةَ": [0],
"عِنْدَهُ": [0],
"berwudhu": [0],
"وَإِهَا": [0],
"berjanji": [0],
"شَاهِدَاكَ": [0],
"يُدْفَعُ": [0],
"اخْتَصَرَهُ": [0],
"سَنِخَةٍ": [0],
"أُوقِدَتْ": [0],
"مُوسِرًا": [0],
"sebelah": [0],
"bapaknya": [0],
"فُلَانٍ": [0],
"kapadaku": [0],
"شَاءُوا": [0],
"nim": [0],
"bangun": [0],
"ambillah": [0],
"اثْنَيْنِ": [0],
"memerdekakanlah": [0],
"بِثْرٍ": [0],
"شَرَطَ": [0],
"اشْتَرِينِي": [0],
"أَمْرِ": [0],
"berharap": [0],
"فَانْكِحُوا": [0],
"فِدَاءَهُ": [0],
"فذكرت": [0],
"suap": [0],
"zakariyya": [0],
"تَسْتَمِينَ": [0],
"rasulullah": [0],
"أَحَبَّ": [0],
"أَحَبُّ": [0],
"berhijablah": [0],
"أَبْصَرْتُهُ": [0],
"tubuhnya": [0],
"ayat": [0],
"mendekatinya": [0],
"ruman": [0],
"bertahannuts": [0],
"rumah": [0],
"menggantinya": [0],
"إِبِلِكُمْ": [0],
"lyas": [0],
"يُقَوَّمُ": [0],
"menebus": [0],
"عَنُوالذكر": [0],
"hushain": [0],
"بَقَاؤُكُمْ": [0],
"فَشَكَانِي": [0],
"فَأَعْتَقَهُ": [0],
"isma\'il": [0],
"أَعْتَقِيهَافَإِنَّمَا": [0],
"مَرْ": [0],
"meletakkan": [0],
"قِيلَ": [0],
"أُمُّ": [0],
"أُمِّ": [0],
"asy-syirkah": [0],
"menjadi": [0],
"yaitu": [0],
"أَرْنِي": [0],
"أَنَّهَا": [0],
"كَلِمِي": [0],
"pekerjaannya": [0],
"هَمَّامٍ": [0],
"katanya": [0],
"هَمَّامِ": [0],
"الْعَصْرَ": [0],
"jarir": [0],
"مَرْهُونًا": [0],
"sesuka": [0],
"sambung": [0],
"وَوَرِثَنِي": [0],
"ketrampilan": [0],
"انْتَهَيْنَا": [0],
"أَنْهَرَ": [0],
"فَلَمَّا": [0],
"rabb": [0],
"kalau": [0],
"الْمُؤْمِسَاتِ": [0],
"إِنَاءٍ": [0],
"أَطْعِمْ": [0],
"membuatkan": [0],
"بِالْمَرَكَةِفَيَشْرَكُمْ": [0],
"paceklik": [0],
"كًا": [0],
"mahar": [0],
"فَاطِمَةُ": [0],
"yutla": [0],
"فَاطِمَةَ": [0],
"دُبُرٍ": [0],
"قَالَخَفَّتْ": [0],
"wajahya": [0],
"انْتَظَرَهُمْ": [0],
"عِلَاجَهُ": [0],
"أَمَّا": [0],
"فَاطِمَةً": [0],
"datang": [0],
"حِمَارًا": [0],
"dihadiahkan": [0],
"now": [0],
"فَدَفَعَ": [0],
"mughirah": [0],
"الْمُصْطَلِقِ": [0],
"الْمَالِ": [0],
"إِيَاسٍ": [0],
"الْمَالَ": [0],
"hisyam": [0],
"waq": [0],
"بِبِينَ": [0],
"sungguh": [0],
"apabila": [0],
"tanganku": [0],
"إِيمَانُ": [0],
"butir": [0],
"حُرَّ": [0],
"إِنَّا": [0],
"karenanya": [0],
"حَمَّادُ": [0],
"حُرِّ": [0],
"وَفَتَاتِي": [0],
"الْمَلِكِ": [0],
"حُرٌّ": [0],
"فَخَرَجَ": [0],
"arqam": [0],
"rasul-nya": [0],
"طَلْحَةً": [0],
"isteri-isteri": [0],
"rafi": [0],
"suka": [0],
"طالبت": [0],
"الْعَرَبِ": [0],
"silakan": [0],
"عروة": [0],
"finnisaa": [0],
"umumnya": [0],
"قَدْوَجَبَ": [0],
"عَامَ": [0],
"نَعَمْ": [0],
"الْغَزْوِ": [0],
"rampasan": [0],
"طَعَامًا": [0],
"الْمُنْذِرِ": [0],
"وَالْقَصْعَةَ": [0],
"مَعَتَكَ": [0],
"banyak": [0],
"ibunya": [0],
"فَيَقُولُ": [0],
"hadiahnya": [0],
"حَتَّى": [0],
"حُرُم": [0],
"tangga": [0],
"sekolah": [0],
"serangkaian": [0],
"يُفْتِي": [0],
"berangkat": [0],
"خَلَفٍ": [0],
"tuannya": [0],
"إِنِّي": [0],
"صحيح": [0],
"mengusap": [0],
"وَأَنَّهُمُ": [0],
"ghossan": [0],
"مَرْوَانَ": [0],
"diam": [0],
"إِسْرَابِيلَ": [0],
"menjualnya": [0],
"kitab": [0],
"أَشَدُّ": [0],
"الْقَصْعَةَ": [0],
"dzat": [0],
"dzar": [0],
"syu\'aib": [0],
"ragu": [0],
"الْقَصْعَةً": [0],
"مَعَ": [0],
"مَرْهُونَا": [0],
"فَجَاءَتْهُ": [0],
"keci": [0],
"يَأْكُلُونَهُ": [0],
"حِلْتُ": [0],
"hawazin": [0],
"bukti": [0],
"suku": [0],
"serang": [0],
"kemari": [0],
"بِوَسْقٍ": [0],
"mengulang": [0],
"تَمْرٍ": [0],
"سَلَتْ": [0],
"raja": [0],
"وَزَعَمَ": [0],
"يَعْمَلُوهَا": [0],
"فَلْيَجْتَنِبُ": [0],
"الْأَقِطِ": [0],
"فَأَتَى": [0],
"mengambil": [0],
"بِخُبْرٍ": [0],
"sama-sama": [0],
"diusahakan": [0],
"فَذَكَرْتُ": [0],
"membalasnya": [0],
"عَدِي": [0],
"زُرْعَةً": [0],
"senantiasa": [0],
"فَأَمَرَتْ": [0],
"شَرِيكَ": [0],
"زُرْعَةَ": [0],
"fulan": [0],
"sajikanlah": [0],
"mengutusnya": [0],
"fudhail": [0],
"bersabar": [0],
"عِمْرَانُ": [0],
"samin": [0],
"صُهُ": [0],
"menikahi": [0],
"rasul": [0],
"بِوَرِ": [0],
"musayyab": [0],
"kitabulloh": [0],
"لأهْلِهَا": [0],
"الضَّبَّ": [0],
"إِلَى": [0],
"فَارْهَنُونِي": [0],
"فَاخْتَصَمْنَا": [0],
"نَدْرِي": [0],
"وَرَسُولِهِ": [0],
"مَعِي": [0],
"مَثَلُ": [0],
"مِثْلَهُ": [0],
"فَحَبَسَهُ": [0],
"مِنكُمْ": [0],
"nya": [0],
"ذِنْبِ": [0],
"الْخَطَّابِ": [0],
"kurban": [0],
"وَرُبَاعَ": [0],
"الْأَشْعَرِي": [0],
"فَنَظَرَ": [0],
"fii": [0],
"الْحَدِيثِ": [0],
"fil": [0],
"diseret": [0],
"kembali": [0],
"جَاءَتْ": [0],
"بَكْرٍ": [0],
"تَصَدَّقُ": [0],
"khalaf": [0],
"أَبَادَرَ": [0],
"giliran": [0],
"تَبَتُ": [0],
"فَقِيلَ": [0],
"keju": [0],
"قِيمَتَهُ": [0],
"barang": [0],
"ab": [0],
"قُرَيْشٍ": [0],
"al": [0],
"أَحْسَنَ": [0],
"an": [0],
"pasukan": [0],
"بَيْنِي": [0],
"as": [0],
"sman": [0],
"hamba": [0],
"az": [0],
"tanggal": [0],
"tinggalkan": [0],
"beribadah": [0],
"be": [0],
"صَوْمَعَتِهِ": [0],
"يَعُودُ": [0],
"tombaknya": [0],
"سَالِمُ": [0],
"تَصْدِيقَ": [0],
"سَالِمٍ": [0],
"عَدَّةٌ": [0],
"bayar": [0],
"إِلَيْهَا": [0],
"سَمْنًا": [0],
"ثَابِتٍ": [0],
"جَارِيَةً": [0],
"menghindari": [0],
"perah": [0],
"جَارِيَةٌ": [0],
"perak": [0],
"أَرْنَبًا": [0],
"عَبْدِي": [0],
"kemudian": [0],
"didalamnya": [0],
"menjelek-jelekkkannya": [0],
"بِرَاحِلَةٍ": [0],
"susu": [0],
"فَأَتَاهُ": [0],
"وَالْقَبِيلَ": [0],
"هشام": [0],
"أَمَرَنَا": [0],
"فَقَالُو": [0],
"يَشْتَرُونَ": [0],
"di": [0],
"وَأُعْتِقَاكِ": [0],
"عَشْرًا": [0],
"ds": [0],
"تَفْعَلُوا": [0],
"murka": [0],
"meriwayatkan": [0],
"membunuhnyadengan": [0],
"ibadah": [0],
"diucapkan": [0],
"orangyang": [0],
"عَبْدًا": [0],
"أَعَيَّرْتَهُ": [0],
"sahrulken1123": [0],
"kedalam": [0],
"karuniakan": [0],
"kepalanya": [0],
"وَقَالَ": [0],
"وَجْهِهِ": [0],
"maulaku": [0],
"شَرْ": [0],
"فَصَنَعَ": [0],
"setiap": [0],
"حُسَيْنٍ": [0],
"ذَبَحُواوَنَصَبُوا": [0],
"darahnya": [0],
"فَعَظْمُ": [0],
"مُكَاتَبَةٌ": [0],
"فَأَخَذْتُهَا": [0],
"يُحْسِنُ": [0],
"سَبْيَهُمْ": [0],
"وَإِلَّا": [0],
"مَنِيًّا": [0],
"selanjutnya": [0],
"يَأْذَنْ": [0],
"أَجْرَانِ": [0],
"جِيرَانُ": [0],
"الْهَدِيَّةَ": [0],
"buruk": [0],
"rati": [0],
"قَالَا": [0],
"عَطِيَّتَهُ": [0],
"جَاءُونَا": [0],
"الْهَدِيَّةِ": [0],
"الْأُولَى": [0],
"menghadiahkan": [0],
"ayahanda": [0],
"الْقَعْقَاعِ": [0],
"an-nu\'man": [0],
"menguatkan": [0],
"غَلَبَكُمْ": [0],
"zakat-zakat": [0],
"menyembunyikan": [0],
"berpikir": [0],
"digital": [0],
"pamong": [0],
"pergi": [0],
"makhramah": [0],
"untuknya": [0],
"rata": [0],
"أَمَتِي": [0],
"بِجَرُورٍ": [0],
"terus": [0],
"tertimpa": [0],
"sebesar": [0],
"sebuah": [0],
"berihram": [0],
"maulana": [0],
"minhal": [0],
"medengarnya": [0],
"مَخْرَمَةَ": [0],
"rumahku": [0],
"mengutus": [0],
"هَنُونِي": [0],
"الْأَحْدَبُ": [0],
"singgah": [0],
"hp": [0],
"الْيَتَامَى": [0],
"عُثْمَانَ": [0],
"hr": [0],
"عُثْمَانُ": [0],
"تُحِبِينَ": [0],
"membawanya": [0],
"شُرُو": [0],
"hadis": [0],
"bagaikan": [0],
"didapatkannya": [0],
"أَتَحَنَّثُ": [0],
"ia": [0],
"كانت": [0],
"id": [0],
"hilal": [0],
"khalid": [0],
"ii": [0],
"il": [0],
"in": [0],
"سَبْيًا": [0],
"anak-anak": [0],
"تَرُدُّ": [0],
"minyak": [0],
"رَضِيَ": [0],
"disebabkan": [0],
"diharamkan": [0],
"terhadap": [0],
"anshar": [0],
"tombak": [0],
"raut": [0],
"azh-zhohran": [0],
"hammad": [0],
"perwallkanmu": [0],
"lestoran": [0],
"كَلِّمِيهِ": [0],
"hammam": [0],
"خَرَقْنَا": [0],
"يَوْمَبِدْ": [0],
"فَطَلَبُوهُ": [0],
"بَعْلِهَا": [0],
"إِبْرَاهِيمَ": [0],
"urusan": [0],
"أَمُوتَ": [0],
"رَسُولَ": [0],
"burdah": [0],
"رَسُولُ": [0],
"إِبْرَاهِيمُ": [0],
"رَسُولِ": [0],
"diambil": [0],
"gaya": [0],
"diri": [0],
"تَا": [0],
"ka": [0],
"أَوْلَادِكُمْ": [0],
"ke": [0],
"dinikahinya": [0],
"يُرْكَبُ": [0],
"bawahnya": [0],
"nantinya": [0],
"buruan": [0],
"كَثِيرٍ": [0],
"niscaya": [0],
"قَوْمِنَا": [0],
"kp": [0],
"وَقَاصِ": [0],
"الدَّجَّالِ": [0],
"مِنْهَالٍ": [0],
"ku": [0],
"وَأَنَا": [0],
"بَشِيرِ": [0],
"ucapan": [0],
"berhenti": [0],
"بَشِيرٍ": [0],
"perlakuklanlah": [0],
"menelan": [0],
"hasilnya": [0],
"كَالَهُ": [0],
"بِشَيْءٍ": [0],
"نُعْطِيَهُ": [0],
"perintahkanlah": [0],
"وَقَاصٍ": [0],
"aqil": [0],
"shahih": [0],
"imran": [0],
"kekurangan": [0],
"dzul": [0],
"وَرَسُولُ": [0],
"حِزْبَيْنِ": [0],
"الْأَنْصَارِيُّ": [0],
"شَاءَ": [0],
"coba": [0],
"وَيُؤَذِي": [0],
"وَاحِدٍ": [0],
"diniatkannya": [0],
"يَمِينُهُ": [0],
"tentangnya": [0],
"الْآيَةُ": [0],
"مَعَهُ": [0],
"بريرة": [0],
"السَّلَمِي": [0],
"الْآيَةَ": [0],
"فَقَتَلَ": [0],
"ma": [0],
"الْيَمِينَ": [0],
"اللَّيْثُ": [0],
"وَالطَّاعَةِ": [0],
"حَمَلَ": [0],
"جَنَّامَةَ": [0],
"mk": [0],
"الْآيَةِ": [0],
"زَمْعَةً": [0],
"mengajak": [0],
"mengajar": [0],
"diletakkan": [0],
"الْهِلَالِ": [0],
"bersedia": [0],
"dibolehkan": [0],
"menyukainya": [0],
"sedang": [0],
"الطَّرْفَاءِ": [0],
"حُلَةٌ": [0],
"aiman": [0],
"syu\'bah": [0],
"أَعْطَاهُ": [0],
"jawaban": [0],
"لِأَهْلِهَا": [0],
"hufaid": [0],
"denagn": [0],
"زَمَنَ": [0],
"memuji": [0],
"no": [0],
"ذَكَرَ": [0],
"dagingnya": [0],
"awza\'ly": [0],
"nu": [0],
"puja": [0],
"beliau": [0],
"المَخْرُومِي": [0],
"jahiliyah": [0],
"بِلَالٍ": [0],
"فَأَبَتْ": [0],
"depan": [0],
"hukumnya": [0],
"مِثْلَ": [0],
"مِثْلُ": [0],
"لِهَذِهِ": [0],
"التَّيْمِي": [0],
"طُولِهَا": [0],
"رِجَالٍ": [0],
"هِشَامٍ": [0],
"النَّجَاشِيَ": [0],
"yazid": [0],
"هِشَامُ": [0],
"sendiri": [0],
"هِشَامِ": [0],
"وَالرُّمْحَ": [0],
"هِشَامٌ": [0],
"فَذُكِرَ": [0],
"سلم": [0],
"tersisa": [0],
"smpn": [0],
"دَخَلَ": [0],
"darinya": [0],
"terhada": [0],
"شَرْطًا": [0],
"حَدَهُ": [0],
"اشْتَرَيْتُ": [0],
"qurban": [0],
"مِمَّنْ": [0],
"saudaranya": [0],
"سَمِعَ": [0],
"فَالْإِمَامُ": [0],
"صَالِحٍ": [0],
"سَلَامٍ": [0],
"salah": [0],
"dipenuhi": [0],
"salam": [0],
"azal": [0],
"ayahnya": [0],
"awanah": [0],
"رَاعٍ": [0],
"jikalah": [0],
"minta": [0],
"pula": [0],
"yusof": [0],
"بَنُو": [0],
"berkat": [0],
"فَبَلَغَ": [0],
"مَرَّاتٍ": [0],
"أَعْطَيْتَ": [0],
"أَعْطَيْتُ": [0],
"berkah": [0],
"menggambarkan": [0],
"فَسَمِعَ": [0],
"qs": [0],
"يَمْنَحُونَ": [0],
"فَأَتَيْتُ": [0],
"kalinya": [0],
"amiin": [0],
"lakmah": [0],
"dikerjakan": [0],
"puji": [0],
"يَخْلِطُهُمْ": [0],
"buatmu": [0],
"أَمْوَالَهُمْ": [0],
"dididiknya": [0],
"dagangan": [0],
"senjata": [0],
"musaddad": [0],
"sebagai": [0],
"عُمْرَةً": [0],
"sa": [0],
"si": [0],
"minum": [0],
"liar": [0],
"حِضْتَهُمْ": [0],
"email": [0],
"يُنْكِحُوهُنَّ": [0],
"menempuh": [0],
"بِفَضْلِ": [0],
"الْمَنْزِلِ": [0],
"بَنِي": [0],
"اسْمُهُ": [0],
"طَالِبٍ": [0],
"الْأَعْمَالُ": [0],
"فَعَلَيْنَا": [0],
"يُقْسَمْ": [0],
"pemgambilan": [0],
"فَأَتَوْا": [0],
"سُولَ": [0],
"نافع": [0],
"memberitahukan": [0],
"memperhatikan": [0],
"pemimpin": [0],
"فَتَوَضَاً": [0],
"أبو": [0],
"seizin": [0],
"يَقْطُرُ": [0],
"يُحَدِّثُ": [0],
"awfaa": [0],
"قُومَ": [0],
"فَاسْتُسْمِيَ": [0],
"ditebus": [0],
"bapakku": [0],
"فَأَصَابَ": [0],
"دُعِيتُ": [0],
"sabdakan": [0],
"mempersaksikannya": [0],
"menyerang": [0],
"kelapangan": [0],
"تَقْرُنُوا": [0],
"bukhari": [0],
"zaid": [0],
"berusaha": [0],
"الرَّجُلُ": [0],
"warisan": [0],
"zuhrah": [0],
"syufah": [0],
"tunggangan": [0],
"لَا": [0],
"mengabari": [0],
"mebebaskan": [0],
"wa": [0],
"الْمِسْوَرَ": [0],
"miswar": [0],
"kuraib": [0],
"لَيْسَتْ": [0],
"kepada": [0],
"ad-dajjal": [0],
"فَسَأَلْنَاهُ": [0],
"حَرَامًا": [0],
"لَيَنْظُرُ": [0],
"bapakmu": [0],
"الْمُدَّعَى": [0],
"الدَّرَاوَرْدِي": [0],
"فَأَعْتَقَتَهَا": [0],
"selama": [0],
"عَلَمَّا": [0],
"matahari": [0],
"sibuk": [0],
"hidupnya": [0],
"jihad": [0],
"الْأَسْوَدُ": [0],
"الْأَسْوَدِ": [0],
"jubair": [0],
"يَدِهِ": [0],
"emas": [0],
"النَّبِي": [0],
"hadyu": [0],
"salim": [0],
"anakku": [0],
"memanggil": [0],
"qiyamul": [0],
"aziz": [0],
"ya": [0],
"نَطْرُ": [0],
"وَكُلُّكُمْ": [0],
"keburukan": [0],
"أُشْهِدُكَ": [0],
"فَأَنْزَلُوهُ": [0],
"lakukan": [0],
"أَعْتَقَ": [0],
"ثَمَنَهُ": [0],
"khadij": [0],
"أَحَدِهِمْ": [0],
"سَمِيدٌ": [0],
"memanggilnya": [0],
"kepayahannya": [0],
"haknya": [0],
"لِي": [0],
"hendaklah": [0],
"perkara": [0],
"mengeraskan": [0],
"haturkan": [0],
"fa\'i": [0],
"يَلْبَسُ": [0],
"menggaulinya": [0],
"فَإِنَّهَا": [0],
"hadirkan": [0],
"كَلَّقْتُمُوهُمْ": [0],
"sangat": [0],
"لَهَبٍ": [0],
"anakmu": [0],
"azib": [0],
"melukainya": [0],
"يُهْدِيَهَا": [0],
"besarnya": [0],
"yusuf": [0],
"marjanah": [0],
"hamid": [0],
"عِنْدَكُمْ": [0],
"حَفْصَةٌ": [0],
"zuhair": [0],
"dituntut": [0],
"penaklukan": [0],
"selain": [0],
"pisaunya": [0],
"حَفْصَةَ": [0],
"dari": [0],
"أَيُّوبُ": [0],
"أَيُّوبَ": [0],
"seterusnya": [0],
"siksa": [0],
"جَعَلَهُمُ": [0],
"زُرَارَةَ": [0],
"وَإِنْ": [0],
"فَشَدَدْتُ": [0],
"mendapatkan": [0],
"وَالرَّجُلُ": [0],
"فَأَعْرَضَ": [0],
"kabur": [0],
"lembah": [0],
"يَةٍ": [0],
"هَؤُلَاءِ": [0],
"أَخَذَ": [0],
"bersama": [0],
"امْرَأَةٌ": [0],
"الْأَعْمَشُ": [0],
"الْأَعْمَشِ": [0],
"أَحَدُنَا": [0],
"فَضَرَبَتْ": [0],
"menyebut": [0],
"bathil": [0],
"sandalku": [0],
"أَهْلُهَا": [0],
"zuhriy": [0],
"فَأَدْرَ": [0],
"interuptus": [0],
"kisah": [0],
"telantar": [0],
"امْرَأَةٍ": [0],
"فَأَثْنَى": [0],
"zakat": [0],
"yahya": [0],
"mengapa": [0],
"tanpa": [0],
"بُرَيْدٍ": [0],
"قُتَيْبَةُ": [0],
"أُنِي": [0],
"menipis": [0],
"ذَلِكِ": [0],
"suaranya": [0],
"ذَلِكَ": [0],
"dilarang": [0],
"kepala": [0],
"panah": [0],
"panggilannya": [0],
"pontang": [0],
"seseorang": [0],
"مُخْتَصَرًا": [0],
"menjelaskan": [0],
"manakah": [0],
"زَوْجِهَا": [0],
"بَيْنَهُمْ": [0],
"bersya\'ir": [0],
"ءَهَا": [0],
"buat": [0],
"يَسَارٍ": [0],
"rombongan": [0],
"keutamaan": [0],
"belas": [0],
"semuanya": [0],
"hanyasanya": [0],
"janganlah": [0],
"فَارْجِعُوا": [0],
"sultan": [0],
"وَسَأَلْنَا": [0],
"كِتَابَتِهَا": [0],
"يَقُلْ": [0],
"bintang": [0],
"مُقَاتِلَتَهُمْ": [0],
"يَنْشُدْنَكَ": [0],
"ihramnya": [0],
"التَّرِ": [0],
"syukur": [0],
"saudaraku": [0],
"surat": [0],
"وَاصِلُ": [0],
"رَبِّهِ": [0],
"sayyidku": [0],
"الزُّهْرِيِّ": [0],
"أَبي": [0],
"أَنَاحرم": [0],
"الرَّهْنَ": [0],
"الرَّهْنُ": [0],
"السَّلَفِ": [0],
"أَوَابِدَ": [0],
"خَرْقًا": [0],
"begini": [0],
"قَوْلِ": [0],
"قَوْلُ": [0],
"أَرَادَ": [0],
"asyraf": [0],
"nu\'man": [0],
"بِضِلَعَيْنِ": [0],
"خَبَأْتُ": [0],
"setelah": [0],
"جَحْشٍ": [0],
"سَلَمَةَ": [0],
"تُقْسِطُوا": [0],
"سَلَمَةً": [0],
"الْفُضَيْلُ": [0],
"lingkungan": [0],
"wanita-wanita": [0],
"yunus": [0],
"prajurit": [0],
"نَصِيبِنَا": [0],
"pedih": [0],
"شَبَبِهِ": [0],
"kebudakannya": [0],
"وَلِيْهَا": [0],
"وَرَوَاهُ": [0],
"berdasarkan": [0],
"buda": [0],
"arab": [0],
"ابْتَاعِي": [0],
"saudara": [0],
"مِنَ": [0],
"أَبُوكَ": [0],
"وَكَانُوا": [0],
"مِنْ": [0],
"seratus": [0],
"أَسْمَاءَ": [0],
"shallallahu": [0],
"pembantu": [0],
"نَسِينَةٌ": [0],
"مَوْلَايَ": [0],
"diriwayatkan": [0],
"imbalan": [0],
"دَخَلَتْ": [0],
"أَتَانَا": [0],
"عُتْبَةَ": [0],
"تَسْتَعِينُهَا": [0],
"فَاسْتَأْذَنَتْ": [0],
"مِنْهَا": [0],
"أَعْدَهَا": [0],
"madinah": [0],
"tsumamah": [0],
"perwaliannya": [0],
"آذَى": [0],
"وَالنَّصِيحَةِ": [0],
"أَحُرُّ": [0],
"لِأَصْحَابِهِ": [0],
"berkewajiban": [0],
"tertarikan": [0],
"رَغْبَةُ": [0],
"فَأَغْلَوْا": [0],
"فَقَرَأَ": [0],
"غُلَامُهُ": [0],
"menebutkan": [0],
"musyrik": [0],
"فَرُبَّمَا": [0],
"يُشِيبُ": [0],
"khatbah": [0],
"بِاللَّهِ": [0],
"بَنُوهُ": [0],
"يَبْلُغُ": [0],
"khususnya": [0],
"قِصَّةُ": [0],
"يُعْتِقَ": [0],
"kejar": [0],
"masih": [0],
"وَضِي": [0],
"khaibar": [0],
"dijadikan": [0],
"tebusan": [0],
"إِنَّهُمْ": [0],
"وَأَصْحَابُهُ": [0],
"buin": [0],
"dibicarakan": [0],
"ثَمَنًا": [0],
"وَمَاتَ": [0],
"إِلَيْهِ": [0],
"syarat": [0],
"الْعَلَاءِ": [0],
"رَبِيعَةَ": [0],
"kepadamu": [0],
"مَانَ": [0],
"bertobat": [0],
"وَنَعْبَتْ": [0],
"الَّذِينَ": [0],
"ذَرَارِيَّهُمْ": [0],
"bakar": [0],
"إِلَيَّ": [0],
"ridha": [0],
"pulang": [0],
"keseluruhan": [0],
"mulutnya": [0],
"kepemilikannya": [0],
"قَدْرَ": [0],
"alaikum": [0],
"أَنَسِ": [0],
"sahaya": [0],
"azrah": [0],
"an-nisaa": [0],
"buku": [0],
"ubaidulloh": [0],
"أَنَسٍ": [0],
"pembebasan": [0],
"سَبِيلِهِ": [0],
"ghulam": [0],
"أَنَسُ": [0],
"menghadap": [0],
"membeli": [0],
"سَمِعْتُ": [0],
"مَالِ": [0],
"عَازِبٍ": [0],
"مَالُ": [0],
"مَالٌ": [0],
"بَنَّا": [0],
"أَتَبَرَّرُ": [0],
"زَابِدَةُ": [0],
"pembagian": [0],
"mengulurkan": [0],
"ketidak": [0],
"تَابَعَهُعَلِيُّ": [0],
"فَرَجَعَتْ": [0],
"berselisih": [0],
"صَاحِبِهِ": [0],
"قَدْدَ": [0],
"قَوْمِ": [0],
"keberkahan": [0],
"quhafah": [0],
"menangkapnya": [0],
"الْغُلَامَ": [0],
"الْغُلَامُ": [0],
"مَنْصُورٍ": [0],
"نَفْسِهَا": [0],
"isra\'il": [0],
"bantuan": [0],
"الْوَاقِعِ": [0],
"ibuku": [0],
"اشْتَرِ": [0],
"terasa": [0],
"فَرَدَّ": [0],
"اشْتَرَ": [0],
"قَدِمْنَا": [0],
"هَنَ": [0],
"وَإِمَّا": [0],
"بِأُمِّهِ": [0],
"فَلَانُ": [0],
"tanyakan": [0],
"وَعَنَابِهَا": [0],
"فَبَيْنَا": [0],
"temui": [0],
"lagi": [0],
"يَسْتَأْذِنَ": [0],
"شَاءَتْ": [0],
"أَرَدْنَا": [0],
"النَّاسُ": [0],
"النَّاسَ": [0],
"وَتَرَكَ": [0],
"النَّاسِ": [0],
"wahai": [0],
"وَابْنُ": [0],
"tiba": [0],
"بِهِمْ": [0],
"عَاصِمٍ": [0],
"النَّارِ": [0],
"عَاصِمُ": [0],
"هَلْ": [0],
"uqbah": [0],
"يَتَحَرَّوْنَ": [0],
"الصَّدَاقِ": [0],
"الْوَلَاءُ": [0],
"الْوَلَاءِ": [0],
"berada": [0],
"مَالِهِ": [0],
"يَزْرَعُوهَا": [0],
"الْوَلَاءَ": [0],
"هَدِيَّةُ": [0],
"tiap": [0],
"وَيُشْرَبُ": [0],
"أَخِي": [0],
"كَيْفَ": [0],
"الشَّاةِ": [0],
"وَحْشِيًّا": [0],
"هَدِيَّةً": [0],
"هَدِيَّةٌ": [0],
"selesai": [0],
"وَاحِدَةً": [0],
"الْمِنْبَرِ": [0],
"berita": [0],
"begitu": [0],
"tetapkan": [0],
"karena": [0],
"لِآلِ": [0],
"lain": [0],
"تُجَاهَهُ": [0],
"lail": [0],
"صُبْحَ": [0],
"صَاحِبُ": [0],
"berisi": [0],
"wahb": [0],
"فَجُمِعَ": [0],
"waha": [0],
"ingin": [0],
"أَسَامَةً": [0],
"أَسَامَةَ": [0],
"فَجَاءُوا": [0],
"فَتَأْكُلُ": [0],
"memberi": [0],
"لَأَنَا": [0],
"ذكرت": [0],
"غَزْوَةِ": [0],
"شُعْبَةُ": [0],
"wala": [0],
"tempo": [0],
"bertahallul": [0],
"shhaih": [0],
"bagian": [0],
"lalu": [0],
"aama": [0],
"يُحَدِّثُكُمْ": [0],
"waki": [0],
"memakan": [0],
"آبَانُ": [0],
"dianggap": [0],
"memakai": [0],
"sahrul": [0],
"tertuduh": [0],
"وَكِيعٌ": [0],
"وَبَيْنَ": [0],
"خَادِمٍ": [0],
"untukmu": [0],
"pakaian": [0],
"لَةٍ": [0],
"مَحِلَهَا": [0],
"musa": [0],
"فَيَلْقَاءَ": [0],
"عَلْقَمَةَ": [0],
"مَنَابِحُ": [0],
"إِيَّاهُ": [0],
"رِجْلَاهُ": [0],
"يُقَامُ": [0],
"دَعَوْنَ": [0],
"karera": [0],
"قَالَتْ": [0],
"lihat": [0],
"الْحَذَاءِ": [0],
"صبح": [0],
"melihat": [0],
"makan": [0],
"فَأُعْتِقَ": [0],
"الْعَزْلَ": [0],
"يُقَالُ": [0],
"mencintai": [0],
"قَضَتْ": [0],
"at-taymiy": [0],
"sugukan": [0],
"terpisah": [0],
"wagid": [0],
"فَارْجِعْهُ": [0],
"hidayah": [0],
"فَأَيُّ": [0],
"marru": [0],
"bertemu": [0],
"أنت": [0],
"thawus": [0],
"perahu": [0],
"kanan": [0],
"berlayar": [0],
"zainab": [0],
"فَأَبَى": [0],
"شَرِيكِي": [0],
"pimpinan": [0],
"pendidikan": [0],
"أَزْوَادُ": [0],
"رَجَاءٍ": [0],
"izin": [0],
"إِلَّا": [0],
"الْجَاهِلِيَّةِ": [0],
"أُمُّهُ": [0],
"وَزَيْدَ": [0],
"tiga": [0],
"لَقَدْ": [0],
"حَجْرٍ": [0],
"umamah": [0],
"عُرَفَاؤُهُمْ": [0],
"أُكْلَتَيْنِ": [0],
"menceritakan": [0],
"زَوْجُهَا": [0],
"merahasiakan": [0],
"sebagiannya": [0],
"ذِرَاعٍ": [0],
"الْأَخِيرُ": [0],
"yatim": [0],
"berjalan": [0],
"an-najasyiy": [0],
"dahulukanlah": [0],
"فَانْطَلَقْتُ": [0],
"abdah": [0],
"مِنْهُمْ": [0],
"الْأَوْزَاعِيُّ": [0],
"humaidiy": [0],
"أهل": [0],
"thuwailah": [0],
"dibebaskan": [0],
"lari": [0],
"وَنَسِيتُ": [0],
"يُونُسُ": [0],
"walinya": [0],
"فَتَايَ": [0],
"قَلِيلًا": [0],
"وَرَسُولَهُ": [0],
"asy-sya\'biy": [0],
"مُحَمَّدٍ": [0],
"مُحَمَّدَ": [0],
"مُحَمَّدُ": [0],
"مُحَمَّدِ": [0],
"fatwa": [0],
"يُونُسَ": [0],
"شَكَ": [0],
"النَّطْعِ": [0],
"tertatih": [0],
"serikatnya": [0],
"إِلَيْهِمْ": [0],
"شُعْبَةَ": [0],
"فَعَجِلُوا": [0],
"ذِرَاعُ": [0],
"sodorkan": [0],
"وَمَنْ": [0],
"مَا": [0],
"jual": [0],
"طَعَامُ": [0],
"لِرَسُولِ": [0],
"غَيْرَمَشْقُوقٍ": [0],
"hal": [0],
"hak": [0],
"مُحْرِمٍ": [0],
"لَهُنَّ": [0],
"أَقْوَامًا": [0],
"تُرِيَهُ": [0],
"keras": [0],
"sahayamu": [0],
"مُحْرِمُ": [0],
"عَنْهُنَّ": [0],
"qasim": [0],
"لَتِسْعَةُ": [0],
"ubaidullah": [0],
"الْعَدْلِ": [0],
"dapat": [0],
"عِبَالِهِمْ": [0],
"الْعَدْلَ": [0],
"asyats": [0],
"أَهْلَكِ": [0],
"majikan": [0],
"عَطِيَّةً": [0],
"عَطِيَّةٌ": [0],
"اشْتَرَى": [0],
"عَطِيَّةَ": [0],
"لَنِي": [0],
"thaoba": [0],
"قَفَلَ": [0],
"مِزْ": [0],
"لُقْمَتَيْنِ": [0],
"وَلَبَنُ": [0],
"فَأَصَبْنَا": [0],
"فَأُكْفِنَتْ": [0],
"perlawanannya": [0],
"يَتَامَى": [0],
"anhuma": [0],
"تَنْكِحُوهُنَّ": [0],
"tubuh": [0],
"أَمْرَكُمْ": [0],
"ucapkan": [0],
"مَالِكٌ": [0],
"مَالِكِ": [0],
"لَنَا": [0],
"مَالِكُ": [0],
"مَالِكَ": [0],
"مَالِكٍ": [0],
"engkau": [0],
"فَأَهْوَى": [0],
"خَرَجْنَا": [0],
"وَأَيْمَانِهِمْ": [0],
"anggota": [0],
"حُلَّةٌ": [0],
"qudamah": [0],
"laut": [0],
"قلضاءُ": [0],
"شَيْبَةً": [0],
"lahab": [0],
"وَقَدْ": [0],
"mundzir": [0],
"خَيْلٌ": [0],
"وَأَنفَسُهَا": [0],
"sebab": [0],
"الْحِجَّةِ": [0],
"حَبَسَ": [0],
"إِسْمَاعِيلُ": [0],
"إِسْمَاعِيلَ": [0],
"melakukan": [0],
"كانَ": [0],
"الْوَجْهَ": [0],
"أَنَّهُمْ": [0],
"jalan": [0],
"عَمْرَهُ": [0],
"lingkungannya": [0],
"anaknya": [0],
"أَبشِيرِ": [0],
"وَلَيْسَ": [0],
"يَرْزُقُنَا": [0],
"pun": [0],
"أَنَّهُ": [0],
"أَن": [0],
"جَابِرَ": [0],
"جَابِرُ": [0],
"جَابِرٌ": [0],
"عِتْقُهُ": [0],
"جَابِرٍ": [0],
"طُوَ": [0],
"جَابِرِ": [0],
"السِّنُ": [0],
"وَأَقْبَلَ": [0],
"حدَانَا": [0],
"مَالِهَا": [0],
"persyaratan": [0],
"suraqah": [0],
"الْغَنَمِ": [0],
"mengejar": [0],
"muhairiz": [0],
"laitsiy": [0],
"persyaratam": [0],
"عَلَيْنَا": [0],
"وَحَمَلَ": [0],
"فَمَنْ": [0],
"رَجَعُوا": [0],
"jangan": [0],
"فَدَعَتْهُ": [0],
"tolong": [0],
"boleh": [0],
"menjawabnya": [0],
"فَقَدْ": [0],
"يَقُولُونَ": [0],
"وَعَنَا": [0],
"سَبْيِ": [0],
"طُوا": [0],
"الْأُخْرَى": [0],
"فَأَخَذْتُهُمَا": [0],
"فَتَكَلَّمَتْ": [0],
"عليه": [0],
"أَحَدَكُمْ": [0],
"kantong": [0],
"السَّوْطَ": [0],
"terakhir": [0],
"طَيَّبْنَا": [0],
"delapan": [0],
"penggantinya": [0],
"juga": [0],
"daftar": [0],
"بَعْثًا": [0],
"kepadaku": [0],
"قُلِ": [0],
"رَافِعَ": [0],
"gulamnya": [0],
"فَعَالَهَا": [0],
"makanan": [0],
"وحَدَّثَنِي": [0],
"عَتَقَ": [0],
"أبيهِ": [0],
"رَافِعِ": [0],
"izinkanlah": [0],
"perang": [0],
"memiliki": [0],
"tadi": [0],
"طِيبًا": [0],
"akulah": [0],
"dibayarkan": [0],
"قُكِ": [0],
"فَأَنْزَلَ": [0],
"فَاكْفِئَتْ": [0],
"uqail": [0],
"asya\'ariy": [0],
"يَهُودِي": [0],
"الْأَعْرَابِي": [0],
"إِبِلًا": [0],
"مِائَةِ": [0],
"hiu": [0],
"اعْجَلْ": [0],
"مِائَةَ": [0],
"مِائَةٍ": [0],
"kubang": [0],
"مِائَةً": [0],
"نُعَيْمٍ": [0],
"sebagian": [0],
"لِيَتِيمَتِهِ": [0],
"pihak": [0],
"syaqiq": [0],
"utbah": [0],
"demikian": [0],
"أَخْمَرَنِي": [0],
"sepanjang": [0],
"بِشْرُ": [0],
"sesoerang": [0],
"عَابِشَةُ": [0],
"تُصُدِّقَ": [0],
"kebutuhan": [0],
"عَابِشَةَ": [0],
"بِشْرٌ": [0],
"تَقَذُرً": [0],
"بِشْرٍ": [0],
"berkomentar": [0],
"keempat": [0],
"يَذْكُرْ": [0],
"bangunan": [0],
"عَابِشَةٌ": [0],
"لِلْعَبْدِ": [0],
"يَقْبِضَ": [0],
"nilai": [0],
"لَحْمًانَضِيجًا": [0],
"ba\'du": [0],
"tantangan": [0],
"ghifari": [0],
"mirip": [0],
"مَاتَ": [0],
"يُكَلِّمَكِ": [0],
"يُطَيِّبَ": [0],
"وَلَكِنَّا": [0],
"teman": [0],
"عليها": [0],
"تُغْنِي": [0],
"وَجَبَ": [0],
"أَعْرَابِيُّ": [0],
"وَأَحْسَنَ": [0],
"jamuan": [0],
"fathimah": [0],
"nomor": [0],
"الْحَجُّ": [0],
"syihab": [0],
"وَرَجُلٍ": [0],
"tercurah": [0],
"daripadanya": [0],
"taqwa": [0],
"غُلَامُكَ": [0],
"dihamparkan": [0],
"لَهُ": [0],
"وَلَيْسَتْ": [0],
"membebaskannya": [0],
"sejak": [0],
"menyampaikan": [0],
"tahu": [0],
"utama": [0],
"أَتَوْا": [0],
"أُنَاسٍ": [0],
"فَلَيْسَ": [0],
"مُسَدَّدٌ": [0],
"seribu": [0],
"فَدُ": [0],
"yakin": [0],
"الْهَدْيَ": [0],
"شُعَيْبٌ": [0],
"dengannya": [0],
"suwaid": [0],
"أَبِيهِ": [0],
"keadilan": [0],
"الْهَدْيِ": [0],
"marah": [0],
"يَمِينٍ": [0],
"عَنْ": [0],
"tujuan": [0],
"bertalbiyah": [0],
"kakekku": [0],
"بَيْنَهُمَا": [0],
"أَوْ": [0],
"sebagaimana": [0],
"خَيْرَ": [0],
"خَيْرٍ": [0],
"سِيرِ": [0],
"لَمْ": [0],
"فَسَأَلْتُهُ": [0],
"يُقْسِطُ": [0],
"serta": [0],
"dihidangkan": [0],
"يُعْطَى": [0],
"الَةَ": [0],
"عَنِ": [0],
"فَيَتَمَتُ": [0],
"كُسُوفِ": [0],
"إِحْرَامِهِوَأَشْرَكَهُ": [0],
"بَعَثَتْ": [0],
"warits": [0],
"menunaikan": [0],
"يَشْتَرِطُونَ": [0],
"abdu": [0],
"sekelompok": [0],
"benar": [0],
"kulakukan": [0],
"menderita": [0],
"digadaikan": [0],
"mencapai": [0],
"الْمَعْرُورَ": [0],
"rawahah": [0],
"طِينٍ": [0],
"tentang": [0],
"أَنْ": [0],
"diperintahkan": [0],
"ahdab": [0],
"أَشْيَاءَ": [0],
"dibebankan": [0],
"talu": [0],
"لَكَ": [0],
"أَنْفَجْنَا": [0],
"الْخَمِ": [0],
"يُوسُفَ": [0],
"كَابِنَةٍ": [0],
"ummul": [0],
"mendo\'akan": [0],
"كَابِنَةٌ": [0],
"sebelum": [0],
"أَمَ": [0],
"adillah": [0],
"أَنَّسٍ": [0],
"أَمْ": [0],
"penuhi": [0],
"ditaksir": [0],
"أَنَّسُ": [0],
"perserikatan": [0],
"penerima": [0],
"جَدِهِ": [0],
"أَرَادُوا": [0],
"zhalim": [0],
"berbunyi": [0],
"شَيْءٍ": [0],
"negeri": [0],
"mas\'ud": [0],
"menunggang": [0],
"عَامِرٍ": [0],
"فَلْيُطْعِمْهُ": [0],
"فَلْيَفْعَلْ": [0],
"فَوَضَعَهُ": [0],
"يَعْنِيالسَّلَاحَ": [0],
"فَاسْتَسْقَى": [0],
"الطَّرِيقِ": [0],
"أَخَاهُ": [0],
"بِنَفَقَتِهِ": [0],
"miliknya": [0],
"khair": [0],
"فَتَنْحَرُ": [0],
"وَجُوَيْرِيَهُ": [0],
"مَعَكُمْ": [0],
"كَلَهَا": [0],
"فِيثَوْبِ": [0],
"كُرَاعُ": [0],
"أَحْمَرَنِي": [0],
"اشْتَرِهَا": [0],
"كُرَاعٍ": [0],
"kecuali": [0],
"tangan": [0],
"teruskan": [0],
"masing-masing": [0],
"فَدَعَاهَا": [0],
"berkumpul": [0],
"umat": [0],
"umar": [0],
"أَثْنَى": [0],
"jatah": [0],
"gilirannya": [0],
"الشُّفْعَةَ": [0],
"سِوَاهُنَّ": [0],
"ثَمَنَ": [0],
"كَأَوَابِدِ": [0],
"tapi": [0],
"فَوْقَنَا": [0],
"lapar": [0],
"dimakan": [0],
"abayah": [0],
"hadapan": [0],
"هُوَ": [0],
"الْعَقْدَ": [0],
"salamah": [0],
"أَنسًا": [0],
"menawan": [0],
"isteri": [0],
"اللَّهُمَّ": [0],
"terhadapnya": [0],
"menyampaikannya": [0],
"beli": [0],
"kaisan": [0],
"فَعَلَيْهِ": [0],
"وَلَقَدْرَ": [0],
"شُرَكَاءَهُ": [0],
"menjawab": [0],
"لَكُمْ": [0],
"لَبَّيْكَ": [0],
"سَفِينَةٍ": [0],
"أَعْتِقِيهَا": [0],
"hidayahnya": [0],
"mushthaliq": [0],
"كُنَّا": [0],
"تَخُطُّ": [0],
"الْعَبَّاسِ": [0],
"sesuai": [0],
"كَمَا": [0],
"menerangkan": [0],
"صلى": [0],
"عَدَلَ": [0],
"pandai": [0],
"هُمْ": [0],
"الظَّهْرَانِ": [0],
"asy-syuf\'ah": [0],
"الْوَارِثِ": [0],
"asma": [0],
"dilakukan": [0],
"أَزْوَاجَهُ": [0],
"baginya": [0],
"أَهْلُكَ": [0],
"tuqsituu": [0],
"celaan": [0],
"سِيرِينَ": [0],
"الْآخَرُلَبَّيْكَ": [0],
"أَيْمَنَ": [0],
"أَيْمَنُ": [0],
"khallad": [0],
"dicampur": [0],
"الْحَبَشَةِ": [0],
"yakni": [0],
"عَنْهَا": [0],
"هَذِهِ": [0],
"مِيبَينِي": [0],
"وَجَدْنَا": [0],
"beri": [0],
"كتاب": [0],
"عَرَضتُ": [0],
"يَبِيعُونِي": [0],
"pembayaran": [0],
"قَتَادَةً": [0],
"قَتَادَةَ": [0],
"الْعَضُدَ": [0],
"الْعُرْبَةُ": [0],
"pergaulan": [0],
"قَتَادَةُ": [0],
"hafshah": [0],
"بِقَصْعَةٍ": [0],
"aslam": [0],
"gadai": [0],
"يَطْعُ": [0],
"حَدَّثَهُ": [0],
"اللهُ": [0],
"semata": [0],
"bertambah": [0],
"اللهِ": [0],
"نِسَاءَكُمْ": [0],
"أَخْصِفُ": [0],
"alaını": [0],
"يُقْسِطُوا": [0],
"رَعِيَّتِهَا": [0],
"عُقْبَةَ": [0],
"maslamah": [0],
"hanya": [0],
"sore": [0],
"abbad": [0],
"dipukul": [0],
"abban": [0],
"الْمُثَنَّى": [0],
"semasa": [0],
"قُلْتُ": [0],
"تَلْقَى": [0],
"mengadakan": [0],
"abbas": [0],
"pengalaman": [0],
"pemilik": [0],
"فَرَ": [0],
"فَرُ": [0],
"manshur": [0],
"akad": [0],
"لِلْأَبَدِ": [0],
"tahun": [0],
"لَوْ": [0],
"مَعْمَرٍ": [0],
"تِهَامَةً": [0],
"مَعْمَرُ": [0],
"bahkan": [0],
"النِّسَاءِ": [0],
"menjadikanku": [0],
"mahasiswa": [0],
"النِّسَاءَ": [0],
"عَارُ": [0],
"besi": [0],
"عُتْبَهُ": [0],
"يُقَومُ": [0],
"اللَّهُ": [0],
"akan": [0],
"اللَّهِ": [0],
"وَسَأُحَدِّثُكُمْ": [0],
"جَمِيعًا": [0],
"اللَّهَ": [0],
"bulan": [0],
"فَضَلَّ": [0],
"صُرِفَتْ": [0],
"وَأَحْسِبُ": [0],
"nisaa": [0],
"سَبِّي": [0],
"صَلَّى": [0],
"disebut": [0],
"سَبِيَّةٌ": [0],
"لَهَا": [0],
"katsir": [0],
"budaknya": [0],
"berkenaan": [0],
"وَالسَّمْنِ": [0],
"النَّمْرَ": [0],
"mungkin": [0],
"tengah": [0],
"فَرَغُوا": [0],
"mengganggu": [0],
"قُلْنَ": [0],
"rakyatnya": [0],
"perempuan": [0],
"cambuk": [0],
"atstsam": [0],
"zaman": [0],
"ijin": [0],
"أُسَامَةً": [0],
"وَأَصَابَ": [0],
"أُسَامَةَ": [0],
"inilah": [0],
"larangan": [0],
"نتبع": [0],
"dirham": [0],
"نَا": [0],
"agama": [0],
"وَالْمَرْأَةُ": [0],
"padahal": [0],
"وَوَلَدِهِ": [0],
"menyelesaikan": [0],
"ahmad": [0],
"menegakkan": [0],
"menjadikan": [0],
"فَأَدْرَكْتُهَا": [0],
"السُّوقِ": [0],
"kelamaan": [0],
"belakang": [0],
"biarkanlah": [0],
"جَرِيرٌ": [0],
"جَرِيرُ": [0],
"بِذَلِكَ": [0],
"mukatab": [0],
"asuh": [0],
"شُرَكَاؤُهُ": [0],
"تَدَعُونَ": [0],
"memberikan": [0],
"فَاعَةً": [0],
"ibn": [0],
"رِفَاعَةَ": [0],
"أَعْلَاهَا": [0],
"ummu": [0],
"jabir": [0],
"بُرْدَةَ": [0],
"بُرْدَةً": [0],
"خَالَةُ": [0],
"abwa": [0],
"mulaikah": [0],
"saudara-saudara": [0],
"depannya": [0],
"masalahnya": [0],
"diijinkan": [0],
"mengendarai": [0],
"بِطَعَامِهِ": [0],
"اسْتَأْذَنَ": [0],
"اللَّأْمَةَ": [0],
"khaththab": [0],
"تُمِنْهُ": [0],
"isinya": [0],
"نَافِعٍ": [0],
"نَافِعُ": [0],
"سَأَلْتُ": [0],
"pemberian": [0],
"piring": [0],
"فَلْنَتْرُكْ": [0],
"pekerjaan": [0],
"pemberiah": [0],
"katakanlah": [0],
"lantas": [0],
"gulamku": [0],
"bermaksud": [0],
"seiring": [0],
"membujang": [0],
"أَعْلَى": [0],
"lebih": [0],
"تَكُونُ": [0],
"أَرَأَيْتَ": [0],
"عَنْهُمَا": [0],
"perbudakan": [0],
"citra": [0],
"memperoleh": [0],
"كُنْتُ": [0],
"لَفِيَّ": [0],
"حَلَفَ": [0],
"خَدِيجٍ": [0],
"وَسَبَى": [0],
"يَتْرُكُوهُمْ": [0],
"أُمَيَّةَ": [0],
"فَاجِرُ": [0],
"يُصِيبُهَا": [0],
"يَعْنِي": [0],
"اسْتَقْبَلْتُ": [0],
"turut": [0],
"أَرْ": [0],
"أَذَى": [0],
"olah": [0],
"turun": [0],
"أَهْلُهُ": [0],
"جِئْتُ": [0],
"مَسْعُودٍ": [0],
"dikatakan": [0],
"saudariku": [0],
"muhammad": [0],
"ثُمَّ": [0],
"adalah": [0],
"شِهَابُ": [0],
"يُذْكَرُ": [0],
"شِهَابٍ": [0],
"يَسِيرَةً": [0],
"أَفْضَلُ": [0],
"umum": [0],
"empat-empat": [0],
"qais": [0],
"يُرِيدُ": [0],
"telah": [0],
"أَرْقَمَ": [0],
"bejana": [0],
"الرَّابِعَةِ": [0],
"فَسَمِعْتُ": [0],
"صُدُورُهَا": [0],
"niat": [0],
"sejenak": [0],
"أَخْبَرَنِي": [0],
"فَيَمِنُوا": [0],
"berfatwa": [0],
"menyelamatkan": [0],
"فَاشْتَرَتْهَا": [0],
"dimasak": [0],
"asy\'ariy": [0],
"menyembelihnya": [0],
"wahbbin": [0],
"أَجْلِ": [0],
"يَأْكُلْ": [0],
"شِرَ": [0],
"يَأْكُلُ": [0],
"شِرْ": [0],
"تَبَيَّنَ": [0],
"بِالنِّيَّةِ": [0],
"يُهْدِيَ": [0],
"فَإِنْ": [0],
"menunjuk": [0],
"بَرِيرَةُ": [0],
"أَخْبَرَنَا": [0],
"sekutu": [0],
"فَقُمْتُ": [0],
"عَبْدٍ": [0],
"مَاهُ": [0],
"خَلِيطَيْنِ": [0],
"عَبْدُ": [0],
"رَغْبَتِهِمْ": [0],
"نَصَحَ": [0],
"عَبْدَ": [0],
"بَرِيرَةً": [0],
"عَبْدً": [0],
"بَرِيرَةَ": [0],
"دِرْهَمًا": [0],
"كَتَبَ": [0],
"syaibah": [0],
"مُسَدَّةٌ": [0],
"mengerjakannya": [0],
"تَدْرِي": [0],
"فَتُقْسَمُ": [0],
"قَوْلِهِ": [0],
"seperti": [0],
"rifa\'ah": [0],
"فَتَعَرَّضَتْ": [0],
"عَلَيْهَا": [0],
"akhirnya": [0],
"oleh": [0],
"melakukanya": [0],
"senggama": [0],
"عَبْدِ": [0],
"perwalian": [0],
"غِبُوا": [0],
"gulammu": [0],
"habasyah": [0],
"sufyan": [0],
"فَرَفَعَتْ": [0],
"atas": [0],
"فَأَ": [0],
"atau": [0],
"مَرَّتَيْنِ": [0],
"keluar": [0],
"mengajaknya": [0],
"kecilnya": [0],
"mendoakannya": [0],
"يُخَلَّى": [0],
"أَتَاكَ": [0],
"فِيهَا": [0],
"سَابَيْتُ": [0],
"ajukanlah": [0],
"عَائِشَة": [0],
"seekor": [0],
"خَوَلُكُمْ": [0],
"الرَّحْمَن": [0],
"الشَّرَكَاءِ": [0],
"kamms": [0],
"بَاطِلُ": [0],
"disebutkan": [0],
"sekitar": [0],
"alamat": [0],
"يَخْرُجُ": [0],
"بِلَحْمٍ": [0],
"سَبِيلُ": [0],
"بِذِي": [0],
"سَبِيلِ": [0],
"أَحْمَدُ": [0],
"tinggi": [0],
"فَإِنَّمَا": [0],
"وَالْتَفَتُ": [0],
"diinginkan": [0],
"budak": [0],
"قَضَاهُ": [0],
"قَسَمَ": [0],
"dinar": [0],
"وَأَعْتَقَ": [0],
"maryam": [0],
"الرسول": [0],
"sosial": [0],
"فَقَالُواائْذَنْ": [0],
"menolakmya": [0],
"يُجِيبَهَا": [0],
"mimbar": [0],
"وَلَنَا": [0],
"سَيِّدِي": [0],
"نَرْجُو": [0],
"وَأُمِرُوا": [0],
"berkhutbah": [0],
"أُعْتِقَ": [0],
"وَرَهَنَهُ": [0],
"ini": [0],
"hewan-hewan": [0],
"quraisy": [0],
"أَنَّسًا": [0],
"سُفْيَانُ": [0],
"سُفْيَانَ": [0],
"pecah": [0],
"perempuannya": [0],
"baginda": [0],
"أَصَابَ": [0],
"وُجُوهَ": [0],
"تَعْمَلْ": [0],
"ratus": [0],
"memerdekakannya": [0],
"dibagi": [0],
"وَسَقًا": [0],
"ayyub": [0],
"menghina": [0],
"بَعْدَ": [0],
"فَهَذَا": [0],
"دَعَاهُمْ": [0],
"عَشَرَةٌ": [0],
"بَعْدُ": [0],
"فَنَا": [0],
"dibebaskannya": [0],
"عَشْرَ": [0],
"بِالْقِسْطِ": [0],
"ketahuilah": [0],
"isma": [0],
"meningal": [0],
"hadzdza": [0],
"قَالُوا": [0],
"pakai": [0],
"barangsiapa": [0],
"عَشَرَةَ": [0],
"khusus": [0],
"حُدُودِ": [0],
"اسْتَأْذَنُوا": [0],
"memang": [0],
"muzara\'ah": [0],
"isri-isteri": [0],
"فَاخْتَارُ": [0],
"وَلَوْلَا": [0],
"أَصْبَحَ": [0],
"diperkuat": [0],
"rasulnya": [0],
"بَعِيرٍ": [0],
"anhum": [0],
"kembalilah": [0],
"جَمَالِهَا": [0],
"الشَّمْسِ": [0],
"maqburiy": [0],
"الشَّمْسُ": [0],
"atha": [0],
"memeluk": [0],
"jawab": [0],
"نَفْسَهَا": [0],
"نَفْسِي": [0],
"فَأَخْبَرُوهُ": [0],
"فَيُعْجِبُهُ": [0],
"فَمَلْتُ": [0],
"qatadah": [0],
"tegas": [0],
"makhlad": [0],
"membayar": [0],
"الْحَكَمِ": [0],
"ditolak": [0],
"فَنِي": [0],
"أَلْبَائِهِمْ": [0],
"الْجَزَاحِ": [0],
"bersamanya": [0],
"petunjuk": [0],
"حَبِيبٍ": [0],
"عُضْرٍ": [0],
"abi": [0],
"فَادَيْتُ": [0],
"tunai": [0],
"الْأَمَةِ": [0],
"حَجَّاجُ": [0],
"hizam": [0],
"الْأَمَةُ": [0],
"رَجُلًا": [0],
"abu": [0],
"التَّمْرُ": [0],
"isa": [0],
"berdiri": [0],
"هَاجَرَ": [0],
"nampan": [0],
"isi": [0],
"كُرَيْبٍ": [0],
"قِيمَةَ": [0],
"غُلَامًا": [0],
"أَنَا": [0],
"زِيَادٍ": [0],
"الْعَزِيزِ": [0],
"فَجَاءَنَا": [0],
"بِضَفِيرٍ": [0],
"قُوْمَ": [0],
"قِيمَةً": [0],
"mengamalkan": [0],
"ibnu": [0],
"perjalanan": [0],
"الصَّعْبِ": [0],
"يَشْتَرِطُوا": [0],
"عَلَيْكُمْ": [0],
"perintahkan": [0],
"tiba-tiba": [0],
"ada": [0],
"وَمَا": [0],
"sha\'bi": [0],
"فَذَكَرَتْ": [0],
"يَتَزَوَّجُهَا": [0],
"اللَّيْتِيَ": [0],
"حَازِمٍ": [0],
"itu": [0],
"شَيْئًا": [0],
"الْحَمِيدِ": [0],
"susunya": [0],
"كَمَثَلِ": [0],
"padaku": [0],
"mutharrif": [0],
"ذَنْبٍ": [0],
"iut": [0],
"الْقَالَةُ": [0],
"berzina": [0],
"الْخَادِمُ": [0],
"جَعَلَ": [0],
"merampok": [0],
"pertama": [0],
"ternyata": [0],
"pasti": [0],
"أَلْفَ": [0],
"نَجَّتِ": [0],
"جَعَلُوهُ": [0],
"dimana": [0],
"يُخْبِرُ": [0],
"ishaq": [0],
"harga": [0],
"أُمَ": [0],
"بَقَاؤُهُمْ": [0],
"sedangkan": [0],
"أُمَّتِي": [0],
"bacalah": [0],
"حَامِدُ": [0],
"فَخَلَا": [0],
"tebusannya": [0],
"اشْتَرَطُوا": [0],
"بَعْضِ": [0],
"berbicara": [0],
"الْمَمْلُوكُ": [0],
"سُنَّةٌ": [0],
"الْمَمْلُوكِ": [0],
"tersebar": [0],
"mengijinkannya": [0],
"lewat": [0],
"cerita": [0],
"الدَّمَ": [0],
"بِكَفِّهِ": [0],
"رِجَالًا": [0],
"baduy": [0],
"أَصُبُ": [0],
"ikan": [0],
"lainnya": [0],
"جَمَعُوا": [0],
"الْعَدُوَّ": [0],
"memilliki": [0],
"nabi": [0],
"qutaibah": [0],
"hadiahkan": [0],
"تَكُنْ": [0],
"عَطَاءِ": [0],
"شُبْتُهُ": [0],
"pisau": [0],
"عَطَاءُ": [0],
"عَطَاءٍ": [0],
"maisarah": [0],
"هِيَ": [0],
"مَرَّةٍ": [0],
"أَشْهَدُ": [0],
"segera": [0],
"bercampur": [0],
"menuju": [0],
"jurusan": [0],
"الْحُمَيْدِيُّ": [0],
"watarghobuuna": [0],
"فَأَقْبَلَ": [0],
"أَهْلِكِ": [0],
"بَاعُونِي": [0],
"وَيَشْرَبُ": [0],
"سَلْنَ": [0],
"مُسْلِمًا": [0],
"مَرَّتْ": [0],
"sallam": [0],
"بِالْقُدُورِ": [0],
"menolak": [0],
"لِجَارَتِهَا": [0],
"milik": [0],
"wajib": [0],
"aim": [0],
"بَلَغَتْ": [0],
"ditakar": [0],
"air": [0],
"سَيِّدَهُ": [0],
"أَيْدِيكُمْ": [0],
"hanyalah": [0],
"apakah": [0],
"dimanfaatkan": [0],
"بِكُلِّ": [0],
"universitas": [0],
"banten": [0],
"الْمَقْرِي": [0],
"وَسَبْيَهُمْ": [0],
"بَدًا": [0],
"أَرْسِلِي": [0],
"pemudiku": [0],
"وَلَهُمْ": [0],
"berpesan": [0],
"kambing": [0],
"مُقَاتِلِ": [0],
"مُقَاتِلٍ": [0],
"زَيْنَبَ": [0],
"زَيْنَبُ": [0],
"أَذِنَ": [0],
"إلى": [0],
"بِنَا": [0],
"menghibahannya": [0],
"فَسَأَلْنَا": [0],
"terletak": [0],
"nafi": [0],
"maupun": [0],
"memburunya": [0],
"khawatir": [0],
"aku": [0],
"نِسَاءَ": [0],
"نِسَاءِ": [0],
"عَنْهُمْ": [0],
"selamanya": [0],
"يَقْبَلُ": [0],
"keturunan": [0],
"وَقَالَتْ": [0],
"sisa-sisa": [0],
"لَأَفْتِنَنَّ": [0],
"نَدَّ": [0],
"ternak-ternak": [0],
"menyusahkan": [0],
"ali": [0],
"secara": [0],
"alaa": [0],
"dzabi": [0],
"تُشْهِدَ": [0],
"tiharmah": [0],
"alu": [0],
"طَيَّبُواوَأَذِنُوا": [0],
"وَلَدٍ": [0],
"الْيَمَانِ": [0],
"فَأَحْسَنَ": [0],
"جُوَيْرِيَةً": [0],
"wajah": [0],
"penulis": [0],
"kecanggihan": [0],
"dza\'bi": [0],
"وَسَوْدَةُ": [0],
"تَرْجِعَ": [0],
"paling": [0],
"عَلِيُّ": [0],
"tunda": [0],
"يَأْتِيَهُ": [0],
"بَشَّارٍ": [0],
"فَحَابًا": [0],
"jalan-nya": [0],
"تُسَمِّ": [0],
"وَاقِدُ": [0],
"nahd": [0],
"didatangi": [0],
"عَلِيِّ": [0],
"kebaikan": [0],
"lincah": [0],
"صَدَقَاتُ": [0],
"تَمَنِهِ": [0],
"hukum": [0],
"tangtangan": [0],
"فَكَانَ": [0],
"دَعَالَهُ": [0],
"lumall": [0],
"كَانُوا": [0],
"dulu": [0],
"وَأَبَقَ": [0],
"za\'idah": [0],
"bertahan": [0],
"حَرْبٍ": [0],
"radiiallahu": [0],
"semester": [0],
"perasan": [0],
"separuh": [0],
"mengikhlaskannya": [0],
"فَأَرْ": [0],
"وَهَلْ": [0],
"maksud": [0],
"ghulamnya": [0],
"tempatnya": [0],
"فَغَضِبْتُ": [0],
"biji-dua": [0],
"pasar": [0],
"وَالظُّفُرَ": [0],
"حِينَ": [0],
"apa": [0],
"alqamah": [0],
"api": [0],
"عِيسَى": [0],
"boin": [0],
"فَكُلُو": [0],
"nyawapun": [0],
"menganggap": [0],
"يُصِيبُنَا": [0],
"menawarkan": [0],
"أَزَالُ": [0],
"مَشْغُولُ": [0],
"akhirat": [0],
"habsasyah": [0],
"أَقْضِيَ": [0],
"menetapkan": [0],
"perbanyak": [0],
"wayastaftuunaka": [0],
"وَيَكُونَ": [0],
"بِهَا": [0],
"العاشر": [0],
"هُمَّ": [0],
"malik": [0],
"suamiku": [0],
"مَنَا": [0],
"sertakanlah": [0],
"statusnya": [0],
"يَكُنْ": [0],
"khianat": [0],
"فَمُدَى": [0],
"الْخُسُوفِ": [0],
"sakiti": [0],
"كُلِّهِ": [0],
"الْحِمَارِ": [0],
"أَبْنَاءَنَافَيُسَبُّ": [0],
"حِزْبُ": [0],
"نَحِلَّ": [0],
"hajji": [0],
"نَبِيكٍ": [0],
"نَخَافُ": [0],
"potong": [0],
"tersebut": [0],
"أَشَيْءٍ": [0],
"diucapkannya": [0],
"terdapat": [0],
"مُطَرِفٍ": [0],
"makkah": [0],
"ketetapanmu": [0],
"siapkan": [0],
"hijjah": [0],
"kabarkan": [0],
"كَأَوَ": [0],
"تريزة": [0],
"غُلَامُ": [0],
"نَرْهَنُ": [0],
"mengangungkan-nya": [0],
"menerimanya": [0],
"ghundar": [0],
"جُرَيْجٌ": [0],
"جُرَيْجٍ": [0],
"menyamakan": [0],
"berwenang": [0],
"mengenakan": [0],
"muntah": [0],
"سَمِعْتُهُ": [0],
"nama": [0],
"aisyah": [0],
"أَهْلِهِ": [0],
"sukai": [0],
"aun": [0],
"زَنَتْ": [0],
"أَصْبَعُ": [0],
"غُلَامٌ": [0],
"aisyat": [0],
"وَلَتْ": [0],
"لِعَا": [0],
"sawdah": [0],
"أَحَدُكُمْ": [0],
"أَقِطًا": [0],
"فَخُذُوهُ": [0],
"إِن": [0],
"berbai\'at": [0],
"بِأَوْ": [0],
"ditentukan": [0],
"keduanya": [0],
"ابْنِي": [0],
"فَرُحْنَا": [0],
"menemuinya": [0],
"وُلِدَ": [0],
"rela": [0],
"kukunya": [0],
"وَيَسْتَفْتُونَكَ": [0],
"perwalia": [0],
"رجَالٍ": [0],
"فَقُلْتُ": [0],
"ارْجِعِي": [0],
"حُفَيْدٍ": [0],
"تُشَارِ": [0],
"suaminya": [0],
"فَأَمَرَتْنِي": [0],
"ayatnya": [0],
"unta": [0],
"dibisikkan": [0],
"samping": [0],
"yang": [0],
"harganya": [0],
"عَنَّامُ": [0],
"فَلْيَعْمَلْ": [0],
"biarlah": [0],
"وَلِي": [0],
"شَرْطُ": [0],
"فَأَمْكَنَتُهُمِنْ": [0],
"مِقْدَامٍ": [0],
"بِهَذَا": [0],
"panasnya": [0],
"ditumpahkan": [0],
"أَنَّ": [0],
"fankihuu": [0],
"فَكَتَبَ": [0],
"سَبْيَنَا": [0],
"harus": [0],
"zam\'ah": [0],
"zakariya": [0],
"فَفَشَتْ": [0],
"usaha": [0],
"cash": [0],
"mis\'ar": [0],
"kedurhakaan": [0],
"pembawa": [0],
"harta": [0],
"cara": [0],
"أَمَرَ": [0],
"melakukannya": [0],
"berjumlah": [0],
"penuh": [0],
"khiftum": [0],
"دَارَةِ": [0],
"kecil": [0],
"memenuhi": [0],
"الدَّرِ": [0],
"بِعُتْبَةَ": [0],
"kalangan": [0],
"masruq": [0],
"يَنْكِحُوا": [0],
"فَلْيُهْدِهِ": [0],
"orang": [0],
"mewajibkannya": [0],
"diriku": [0],
"radiallahu": [0],
"bagikan": [0],
"semacam": [0],
"sekali": [0],
"فَوْقَهُمْ": [0],
"berhak": [0],
"أَيْضًا": [0],
"عُمَرَوَابْنُ": [0],
"disabdakan": [0],
"وَإِنَّهُمْ": [0],
"نَوَى": [0],
"dirawat": [0],
"يَوْمِي": [0],
"shadaqah": [0],
"وَلَا": [0],
"صَدَقَاتُهُمْ": [0],
"فَعَمَدَ": [0],
"ikut": [0],
"keluarga": [0],
"وَأَضُبًا": [0],
"فَبَقِي": [0],
"pokok": [0],
"عُبَيْدَةَ": [0],
"tulang": [0],
"إِلَيْهِنَّ": [0],
"pemudaku": [0],
"وَغُلَامِي": [0],
"نَارُ": [0],
"طَهْمَانَ": [0],
"pengembala": [0],
"أَسْلَمَ": [0],
"اللَّهُعَلَيْهِ": [0],
"الْمُهَاجِرِينَ": [0],
"يَزِيدَ": [0],
"فَرَعُوا": [0],
"menadapat": [0],
"kemiripannya": [0],
"jatstsamah": [0],
"قُدَامَةَ": [0],
"يَزِيدُ": [0],
"uwaisiy": [0],
"اسْتَدْبَرْتُ": [0],
"زَيْدٍ": [0],
"بِالْعَتَاقَة": [0],
"membuat": [0],
"memukul": [0],
"janji": [0],
"زَيْدُ": [0],
"menolaknya": [0],
"زَيْدِ": [0],
"الَّذِي": [0],
"نَسِيتَةً": [0],
"رواه": [0],
"عُمَرُفَأَخْبَرُوهُ": [0],
"adam": [0],
"profil": [0],
"يَوْمًا": [0],
"kini": [0],
"muslimah": [0],
"berdamai": [0],
"بَالُ": [0],
"buraid": [0],
"sesuatu": [0],
"binatang": [0],
"نِسَاءَكَ": [0],
"البخاري": [0],
"تُكَلِّفُوهُمْ": [0],
"أَهْدَى": [0],
"مَسْئُولٌ": [0],
"جاءَتْ": [0],
"permasalahan": [0],
"شَقِيقٍ": [0],
"وَإِبِلًا": [0],
"يُكَلِّمُ": [0],
"رَاعِيًا": [0],
"عُبَيْدٍ": [0],
"يَقُولُ": [0],
"riwayat": [0],
"عُبَيْدُ": [0],
"عُبَيْدِ": [0],
"saw": [0],
"فَهِجْرَتُهُ": [0],
"حُصَيْنٍ": [0],
"an-nadhar": [0],
"أَمْسَى": [0],
"الشَّعْبِي": [0],
"جَبَلَةُ": [0],
"فَخَيْرَهَا": [0],
"keletihan": [0],
"لِكَعْبِ": [0],
"hajjinya": [0],
"نَادِ": [0],
"جَبَلَةَ": [0],
"melahirkan": [0],
"ma\'mar": [0],
"bab": [0],
"bad": [0],
"مَخْلَدٍ": [0],
"مُحَاضِرُ": [0],
"زُهَيْرُ": [0],
"ketaatan": [0],
"bermajelis": [0],
"matikan": [0],
"ikhlaskan": [0],
"muncul": [0],
"zurai": [0],
"kelompok": [0],
"menghitung": [0],
"يُقَوَمُ": [0],
"حَدَّثَاهُ": [0],
"kecantikannya": [0],
"perkembangan": [0],
"sahabatnya": [0],
"عَمْرِو": [0],
"مَاءِ": [0],
"mencarinya": [0],
"menjaminkan": [0],
"humaid": [0],
"kiri": [0],
"اسْقِ": [0],
"فَأَبْصَرُ": [0],
"سَعْدِ": [0],
"utusan": [0],
"keinginan": [0],
"سَعْدُ": [0],
"سَعْدٍ": [0],
"bagiannya": [0],
"sahabat": [0],
"فَيُعْتِقُ": [0],
"sekalipun": [0],
"فَرَضَ": [0],
"أَسْلَمْتَ": [0],
"غُلَامِهِ": [0],
"فِرْ": [0],
"فَرَغَ": [0],
"zur\'ah": [0],
"terbuat": [0],
"mengharap": [0],
"كِيعُ": [0],
"bodoh": [0],
"coitus": [0],
"terima": [0],
"مِنْمَالُ": [0],
"shahabat": [0],
"مُرِي": [0],
"kewajiban": [0],
"الْيَهُودَ": [0],
"كِتَابِ": [0],
"فَذَهَبَ": [0],
"سَهْلِ": [0],
"وَأَمَّا": [0],
"berlaku": [0],
"قَالَهُ": [0],
"غَسَّانَ": [0],
"الظُّفُرُ": [0],
"الظُّفُرَ": [0],
"munabbih": [0],
"جَزُورًا": [0],
"dimuntahkannya": [0],
"اقْتَسَمُوهُ": [0],
"radliallahu\'anhu": [0],
"kita": [0],
"shalih": [0],
"فَزَعَمَتْ": [0],
"مَسْرُوقٍ": [0],
"hijrah": [0],
"فَإِذَا": [0],
"dirimu": [0],
"kelelahan": [0],
"أُهْدِيَ": [0],
"إِنَّهَا": [0],
"hijrahnya": [0],
"أَسْفَلَهَا": [0],
"أَعْطَانِي": [0],
"فَيَشْتَرِي": [0],
"مَمْلُوكٍ": [0],
"tinggal": [0],
"أَغَارَ": [0],
"مَمْلُوكُ": [0],
"يَمْنَعُكِ": [0],
"قِيمَةٌعَدْلٍ": [0],
"كَتَبْتُ": [0],
"menduga": [0],
"mengatakan": [0],
"تَدَعُ": [0],
"adil": [0],
"sha": [0],
"جَعُهُ": [0],
"نَعْلِي": [0],
"وَلِتُهَا": [0],
"لِعُرْوَةَ": [0],
"اترك": [0],
"kehadiran": [0],
"يَرْكَبُ": [0],
"ilah": [0],
"عُرَفَاؤُكُمْ": [0],
"الْوَرِقَ": [0],
"seandainya": [0],
"wahyu": [0],
"فَكُلُوهُلَيْسَ": [0],
"مِمَّا": [0],
"kain": [0],
"فِيهِمْ": [0],
"kalian": [0],
"وَلَاءَهَا": [0],
"aswad": [0],
"katakan": [0],
"قِيمَهُ": [0],
"padanya": [0],
"menjauhi": [0],
"memaki-makinya": [0],
"أُكِلَ": [0],
"alachi": [0],
"keledai": [0],
"luma": [0],
"وَلَدِكَ": [0],
"حَكِيمَ": [0],
"فُضَيْلٍ": [0],
"الْكَلَامُ": [0],
"membunuhnya": [0],
"إِبِلِهِمْ": [0],
"dimilki": [0],
"وَمَسْئُولٌ": [0],
"bin": [0],
"بِمُهُ": [0],
"kaki": [0],
"lupa": [0],
"kekufuran": [0],
"laits": [0],
"تَعَالَى": [0],
"أَصْحَابِ": [0],
"وَإِنْأَخَذُوا": [0],
"بِالْأَبْوَاءِ": [0],
"الْعَابِدُ": [0],
"biy": [0],
"فَرَدَ": [0],
"utsman": [0],
"أَهَلَّ": [0],
"كَرَ": [0],
"sulaiman": [0],
"فَلْتَفْعَلْ": [0],
"termasuk": [0],
"thowus": [0],
"istilah": [0],
"بِعَبْدِ": [0],
"المَوَالِي": [0],
"diragukan": [0],
"الطَّابِفَتَيْنِ": [0],
"أَخَرَهَا": [0],
"kami": [0],
"كُنَا": [0],
"لِوَجْهِ": [0],
"فَأَمَرَ": [0],
"عَبَايَةَ": [0],
"sma": [0],
"الْجَيْشِ": [0],
"sayur": [0],
"sabiilillah": [0],
"kamu": [0],
"حُوتُ": [0],
"abdiy": [0],
"رَجُلٌ": [0],
"رَجُلٍ": [0],
"berjumpa": [0],
"أَهْلِ": [0],
"فَنُهُوا": [0],
"أُنْزِلَتْ": [0],
"غَازُونَ": [0],
"kali": [0],
"perwalikannya": [0],
"غَدًا": [0],
"اسْتَنْقَذَ": [0],
"الْجَيْسُ": [0],
"minuman": [0],
"فَعَلْتُ": [0],
"وَأَيُّمَا": [0],
"فَحَدَّثَنِي": [0],
"mencari": [0],
"amal": [0],
"bantulah": [0],
"pernikahanku": [0],
"وَصَفِيَّةٌ": [0],
"berarti": [0],
"urwah": [0],
"بَيْعِ": [0],
"بَكْرٍرَضِيَ": [0],
"فَاشْتَدَّتْ": [0],
"ثَوْبِ": [0],
"وَأَبُو": [0],
"jiwaku": [0],
"kapal": [0],
"ibrahim": [0],
"حِصَصَهُمْ": [0],
"kawannya": [0],
"فَبَاعَهُ": [0],
"أَرَادَتْ": [0],
"sampai": [0],
"berperang": [0],
"اسْمَاعِيلَ": [0],
"الْجِهَادُ": [0],
"لَيْسَ": [0],
"أَنَّهُمَا": [0],
"athiyyah": [0],
"sembelihan": [0],
"sunnah": [0],
"perwallanmu": [0],
"malam": [0],
"خَادِمُهُ": [0],
"hatinya": [0],
"ذَهَبٍ": [0],
"فَاشْتَرَطَ": [0],
"pertanian": [0],
"الْمُعْتَقِ": [0],
"ilir": [0],
"أَهْدَيْتُ": [0],
"menikahinya": [0],
"بَلَغَهُ": [0],
"كُنَّ": [0],
"عِنْدَهُمْ": [0],
"قَدِمَ": [0],
"فَضْلَهُ": [0],
"kurma": [0],
"sehingga": [0],
"tentu": [0],
"kejadiannya": [0],
"kab": [0],
"نَجَّارُ": [0],
"total": [0],
"جُوَيْرِيَهُ": [0],
"بِأَزْوَادِ": [0],
"الْأُوَيْسِيُّ": [0],
"فَقْدَهَا": [0],
"terkumpul": [0],
"kar": [0],
"فَاخْتَارَتْ": [0],
"شَقِيصًا": [0],
"hak-haknya": [0],
"hendak": [0],
"mendapat": [0],
"عَقِيلًا": [0],
"kuali": [0],
"tertarik": [0],
"demi": [0],
"فَاحْتَمَلَهُ": [0],
"رَأَى": [0],
"الْمَكْسُورَةَ": [0],
"الْغَنَمِبِبَعِيرٍ": [0],
"مُهِلِينَ": [0],
"صَوْتَهَا": [0],
"قَالَ": [0],
"ضَرَبَ": [0],
"qa\'qa": [0],
"wuhaib": [0],
"مُلَيْكَةً": [0],
"تُعِينُ": [0],
"cambuklah": [0],
"طَا": [0],
"ubaidah": [0],
"belilah": [0],
"طَلَعَ": [0],
"فَلَيُنَا": [0],
"berbicaralah": [0],
"dipimpinnya": [0],
"ketentuan": [0],
"كُلُّهُ": [0],
"alhamdulillah": [0],
"احب": [0],
"masuk": [0],
"وَهُمْ": [0],
"berbuat": [0],
"رُهِنَ": [0],
"tertentu": [0],
"mengetahui": [0],
"keadaan": [0],
"setudy": [0],
"وَذُكِرَ": [0],
"الْقَوْمُ": [0],
"ذَرٍ": [0],
"الْقَوْمِ": [0],
"مِائَهُ": [0],
"ketiga": [0],
"ilmu": [0],
"terdiri": [0],
"حَجْرِهِ": [0],
"يَتَرَاجَعَانِ": [0],
"panggillah": [0],
"muslimun": [0],
"kec": [0],
"فَأَعْطَيْتُهُ": [0],
"mengeluarkan": [0],
"الْقِيَامَةِ": [0],
"وَهُوَ": [0],
"tuan": [0],
"وَسَلَّمَ": [0],
"kaum": [0],
"وَفِيَّةٌ": [0],
"دَارَ": [0],
"وَسَلَّمْ": [0],
"الْأَيْمَنُونَ": [0],
"دَارِ": [0],
"قَامَ": [0],
"hazim": [0],
"بِالسَّوِيَّةِ": [0],
"لَأَجَبْتُ": [0],
"bilal": [0],
"melihatnya": [0],
"dinyalakan": [0],
"يُقَةِ": [0],
"طِي": [0],
"نُعَتِمٍ": [0],
"فَكَلَّمَتْهُ": [0],
"kata": [0],
"peminat": [0],
"بَعْضُهُمْ": [0],
"bebaskanlah": [0],
"amir": [0],
"شَكُوا": [0],
"diinjak": [0],
"setia": [0],
"الزُّهْرِي": [0],
"بِالشَّفْعَةِ": [0],
"menggadaikan": [0],
"إِنَّهُ": [0],
"hutan": [0],
"menanyakannya": [0],
"جَانَةً": [0],
"لُقَمَةٌ": [0],
"جَالِسٌ": [0],
"الطَّرْقُ": [0],
"disibukkan": [0],
"suami": [0],
"awaisiy": [0],
"swt": [0],
"فَأَتْبَهَا": [0],
"إِذَا": [0],
"mengapakah": [0],
"biawak": [0],
"sementara": [0],
"جَانَةَ": [0],
"فَأَبَوْا": [0],
"الْفَرَسِ": [0],
"سَلَّمَ": [0],
"وَلَوْ": [0],
"أَرُدَّ": [0],
"أَفَتَذْبَحُ": [0],
"فِرَاشِهِ": [0],
"merdeka": [0],
"temanku": [0],
"مَرْحُومٍ": [0],
"فَأَعْتَقْتُهُ": [0],
"ma\'an": [0],
"خُصُومَةٌ": [0],
"فَاجْلِدُوهَا": [0],
"gerhana": [0],
"abdulla.h": [0],
"pedang": [0],
"فَأَعْطَى": [0],
"ketika": [0],
"memberiku": [0],
"بَعِي": [0],
"didengar": [0],
"غَنَمًا": [0],
"ارْ": [0],
"hulaifah": [0],
"kayu": [0],
"wahid": [0],
"خَالِدٍ": [0],
"تَحْتَهُمَا": [0],
"خَالِدُ": [0],
"laki-laki": [0],
"مَرْضَاةَ": [0],
"تَكَلَّمْ": [0],
"الْفَتْحِ": [0],
"تَكَلَّمُ": [0],
"بَلْ": [0],
"mencukupi": [0],
"paraj": [0],
"وَسَأَحَدَتُكُمْ": [0],
"الطَّيبَ": [0],
"عَشْرَةَ": [0],
"kewajibannya": [0],
"dadanya": [0],
"diterima": [0],
"setuju": [0],
"firman": [0],
"menurunkan": [0],
"normal": [0],
"abdurrahman": [0],
"فَأَعْتِقِيهَا": [0],
"يُصَلِّي": [0],
"miqdam": [0],
"wasallam": [0],
"عُمَرَ": [0],
"وَسْقَيْنِ": [0],
"amma": [0],
"عُمَرُ": [0],
"sekaligus": [0],
"أُخْتِي": [0],
"ad-darawardiy": [0],
"يُسْتَسْعَ": [0],
"تَقُولُ": [0],
"كَالْكَلْبِ": [0],
"تُسْقَى": [0],
"وَلَمْ": [0],
"sahal": [0],
"namun": [0],
"وَمَعَهُ": [0],
"memerdekkan": [0],
"sisa": [0],
"lubangi": [0],
"بَيْنَ": [0],
"أسامة": [0],
"anjing": [0],
"زُرَيْعٍ": [0],
"ghulamku": [0],
"فَأَعْتَقِيهَا": [0],
"مُحَيْرِ": [0],
"وَأُعْتِقَ": [0],
"أُتِيَ": [0],
"pendapat": [0],
"keutamaanya": [0],
"فَأَذِنَ": [0],
"بِالْحَجَ": [0],
"saat": [0],
"وَأَنْ": [0],
"ducapkan": [0],
"amru": [0],
"وَغَنَمًا": [0],
"تَمَتَكِ": [0],
"يَبْلُغُوا": [0],
"marwan": [0],
"وَفَدُ": [0],
"عَبْدَكِ": [0],
"مْرِي": [0],
"membebaskan": [0],
"silahkan": [0],
"kubangan": [0],
"goda": [0],
"muhajirin": [0],
"shalat": [0],
"tawanan": [0],
"الصَّرْفِ": [0],
"عَمْرَةُ": [0],
"sampaikan": [0],
"عَمْرَةَ": [0],
"menyembelih": [0],
"umarah": [0],
"dirinya": [0],
"أَجْمَلُ": [0],
"antankihuuhunna": [0],
"وَعَنْ": [0],
"أَبْنَاءَكُمْ": [0],
"فحمد": [0],
"مَشْقُوقٍ": [0],
"لَوْلَا": [0],
"مَعْنُ": [0],
"صَدَقَ": [0],
"فَرِيضَةَ": [0],
"yaman": [0],
"أَهَدِيَّةٌ": [0],
"suatu": [0],
"اسْمُ": [0],
"ابْنِ": [0],
"هَلَكُوا": [0],
"ابْنُ": [0],
"ابْنَ": [0],
"عَمْرٍو": [0],
"وَمَشَيْتُ": [0],
"dilahirkan": [0],
"الْكُفْرِ": [0],
"juallah": [0],
"فَاصْنَعُوا": [0],
"tak": [0],
"فَنَذْبَحُ": [0],
"ثَقُلَ": [0],
"حَيْثُ": [0],
"makanannya": [0],
"pembenaran": [0],
"تَنَا": [0],
"أَسْكَتَتْهَا": [0],
"terputus": [0],
"بَيْتِهِ": [0],
"غَيْرُهُ": [0],
"لهَا": [0],
"حَاتِمُ": [0],
"shafiyyah": [0],
"hambasahaya": [0],
"وَفَادَيْتُ": [0],
"اسْتَقَوْا": [0],
"dimaksud": [0],
"sumpah-sumpah": [0],
"abdul": [0],
"أَبَرُّ": [0],
"memasak": [0],
"عَبْدَهُ": [0],
"وَتَرَوْجَهَا": [0],
"dijawab": [0],
"abdur": [0],
"وَأَتْقَى": [0],
"mumair": [0],
"عَمْرُو": [0],
"كَسَرُ": [0],
"فَنَدَّ": [0],
"muhadhir": [0],
"فَنَزَلْتُ": [0],
"بِتْرِ": [0],
"sholawat": [0],
"النَّبِيِّ": [0],
"pemimipin": [0],
"النَّبِيُّ": [0],
"النَّبِيَّ": [0],
"فَاشْتَدَّ": [0],
"putri": [0],
"meringkasnya": [0],
"تُصِبْهُمَا": [0],
"dariku": [0],
"يُؤْذِنُونِي": [0],
"basysyar": [0],
"أَصْلَاعِهِ": [0],
"عَبْدَهَا": [0],
"pemeliharaku": [0],
"perbuatan": [0],
"keutamaannya": [0]
};
